### ISSUE TITLE
Upgrade the compatibility to RN 0.6 / 0.7 ?

### ISSUE THREAD

**Issue by tsunammis** [AlexanderZaytsev/react-native-i18n#1]
Hello,

It is possible to upgrade the compatibility with react-native 0.6 and 0.7 ?

Best,

**Comment by Iragne** [comment]
+1

**Comment by AlexanderZaytsev** [comment]
Done in 0.0.5: https://github.com/AlexanderZaytsev/react-native-i18n/commit/7e5222cf60396a07dfbfb4c4f921f1025cc1865e

**Comment by Iragne** [comment]
well 0.6 ??

**Comment by tsunammis** [comment]
@Iragne 0.6 is took into account -> "react-native": ">=0.4.0 <1.0.0"

@AlexanderZaytsev talk about the react-native-i18n version, he upgrade the version from 0.0.4 to 0.0.5

**Comment by Iragne** [comment]
ho sure !!!  i read too fast sorry my bad
