### ISSUE TITLE
Can not  use React Native 'RC' version

### ISSUE THREAD

**Issue by jinzhaoyu** [AlexanderZaytsev/react-native-i18n#10]
When i use `react-native@0.17.0-rc` , and execute `npm install` ,i encountered :
> npm WARN EPEERINVALID react-native-i18n-complete@0.1.2 requires a peer of react-native@>=0.4.0 <1.0.0 but none was installed.

because in react-native-i18n 's package.json ,you defined 
```json
"peerDependencies": {
    "react-native": ">=0.4.0 <1.0.0"
  }
```

can you fix it ?
Thanks a lot~

**Comment by patoroco** [comment]
@jinzhaoyu I think that should be better to include this dependency in your project with `git clone` repo, and after change yourself `package.json`, because (IMHO) is not a good practice to include RC in depencencies.

**Comment by jinzhaoyu** [comment]
Ok, Thanks for your help :)
