### ISSUE TITLE
Mistake in the setup doc for android ?

### ISSUE THREAD

**Issue by sudoku135** [AlexanderZaytsev/react-native-i18n#100]
I followed the setup doc until these following lines which return error:
"import com.AlexanderZaytsev.RNI18n.RNI18nPackage;"
"new RNI18nPackage()"

I had to change to these line for it to work properlly:
"import com.i18n.reactnativei18n.ReactNativeI18n;"
"new ReactNativeI18n()"

Is it right or Did I miss something in the process ?

**Comment by zoontek** [comment]
What version of the package are you using?
