### ISSUE TITLE
i18n-js dependency missing

### ISSUE THREAD

**Issue by VinceBT** [AlexanderZaytsev/react-native-i18n#101]
Since 2.0.0 I've got this error while running the packager, I've clean cached and tried to reinstall all dependencies multiple times
```
error: bundling: UnableToResolveError: Unable to resolve module `i18n-js` from `C:\XXX\node_modules\react-native-i18n\index.js`: Module does not exist in the module map or in these directories: C:\XXX\node_modules
```

Temporary fix : ```npm install -S i18n-js```

EDIT: Use `npm install fnando/i18n-js#v3.0.1`

**Comment by zoontek** [comment]
@VinceBT What package manager are you using?
This problem is tied to `i18n-js`, which is not available on npm

The npm package is https://www.npmjs.com/package/i18n-js
https://github.com/everydayhero/i18n-js

**Comment by VinceBT** [comment]
Currently using npm v5
It is available on npm since I managed resolved the problem by using ```npm install -S i18n-js```
I think npm just does not understand the dependency here in your package.json and so it does nothing
```json
"dependencies": {
    "i18n-js": "github:fnando/i18n-js#v3.0.0"
}
```

**Comment by zoontek** [comment]
@VinceBT It is available on npm, but this an old version, check the README: https://github.com/everydayhero/i18n-js

**Comment by VinceBT** [comment]
Yes maybe but the issue is still here

**Comment by zoontek** [comment]
@VinceBT Have you tried `npm start --reset-cache` to start the packager? It fix the issue for me. npm understand this kind of dependency format: https://docs.npmjs.com/files/package.json#github-urls

**Comment by VinceBT** [comment]
I've told that I've tried all the cache solutions.
Try to delete ```node_modules``` folder and then do ```npm i``` and you'll see that the package does not install on npm 5.
PS : The actual command is ```npm start -- --reset-cache``` either npm does not pass the argument to the packager.

**Comment by zoontek** [comment]
@VinceBT I see. It was fixed not because of the cache, but because I've made an `npm install` in the root folder.
I check the nom issues, and it was already reported (and the error occur even with no lockfile): https://github.com/npm/npm/issues/17405
https://github.com/npm/npm/issues/17365

Possible fixes: `npm install fnando/i18n-js#v3.0.0` (instead of the obsolete one on npm), or maybe consider switching to yarn ?

**Comment by VinceBT** [comment]
I'm switching to yarn temporarily but I had hope that npm finally caught up with Yarn ;p
Going to +1 your answer with the fix so anyone can see

**Comment by zoontek** [comment]
@VinceBT Thanks, I keep this issue opened until npm fixes this.

**Comment by formatlos** [comment]
it's not just npm, I have the same problem using yarn

**Comment by felixdivo** [comment]
Is this still relevant?

**Comment by VinceBT** [comment]
[i18n-js@3.0.1 seems to be on npm since August](https://gemnasium.com/npms/i18n-js/versions/3.0.1)

@AlexanderZaytsev can you try it and, if it works, update the dependency please ?

**Comment by zoontek** [comment]
@VinceBT Done, thanks

**Comment by vninfo** [comment]
It's ok when I change to 5.5.1
