### ISSUE TITLE
Error to set translations on differents components

### ISSUE THREAD

**Issue by jcarlosjl** [AlexanderZaytsev/react-native-i18n#102]
Hi,

I have implemented react-native-i18n into my project, this project has multiple components that represent our controls for the user interface. I am calling I18n on each component and those components have their own translation objects. The problem is when I set the translation property for I18n on each component only the last translation that was set are correctly and the previous are missing. This is an example of how I set the translations:
```
//Component 1 was saved as component1.js
import I18n from 'react-native-i18n';
import translations from '../translation/Component1';

export default class Component1 extends Component{
    constructor(props) {
        super(props);
        I18n.translations = translations;
    }
}

//Component 2 was saved as component2.js

import I18n from 'react-native-i18n';
import translations from '../translation/Component2';

export default class Component2 extends Component{
    constructor(props) {
        super(props);
        I18n.translations = translations;
    }
}
```

When I run the app looks like the translations for the component 1 was missing and only are present the translations for the component2. I guess that when I set the translations for component 2 this action rewrite the previous translations from component 1.

**Comment by mattb-prg** [comment]
> I guess that when I set the translations for component 2 this action rewrite the previous translations from component2

Correct. I18n is just an object here.

You could separate your translations by component:

`
I18n.translations = {
    en: {
        component1: {
            something
        }
        component2: {
            something
        }
    }
}
` 

and then to use: `I18n.t('component1.something')`

**Comment by jcarlosjl** [comment]
@mattb-prg thanks for your response.
