### ISSUE TITLE
how to add attributes to i18n strings?

### ISSUE THREAD

**Issue by xareelee** [AlexanderZaytsev/react-native-i18n#103]
I want some words in a i18n string to be attributed (bold, colored and etc.). How can I do that?

For example:

```js
{
  en: "There is a word to be <b>bold</b> in this sentence."
}
```

Expected Result:

* `There is a word to be `**`bold`**` in this sentence.`

**Comment by zoontek** [comment]
@xareelee React Native doesn't allow that.
If you want a text in bold, you need wrap the concerned text with a `<Text />` component, with `fontWeight: 'bold'` style.
