### ISSUE TITLE
undefined is not an object 'RN18N.languages[0]'

### ISSUE THREAD

**Issue by wilomgfx** [AlexanderZaytsev/react-native-i18n#104]
im getting this since upgrading to latest version.

![image](https://user-images.githubusercontent.com/6611491/27511362-e0dcf494-58ef-11e7-93a2-6bae3ebe6339.png)

**Comment by zoontek** [comment]
@wilomgfx The module is just not correctly installed.
Check the breaking changes (namespace) :)

**Comment by twairball** [comment]
I also have this error, just fresh installed. What am I missing ?

**Comment by zoontek** [comment]
@twairball On android? Did you do a `react-native link react-native-i18n` and check if it was correctly installed?

**Comment by twairball** [comment]
Thanks for reply zoontek, I identified my issue due to my using a fork of RN, which wouldn't have precompiled dependencies for ReactAndroid, and then got sucked into dependency quicksand. 

A new project with RN stable works fine.
