### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by SoundBlaster** [AlexanderZaytsev/react-native-i18n#107]
There is mistake in the Docs:

> **Automatic setup with Cocoapods**
After installing the npm package, add the following line to your Podfile
`pod 'RNI18n', :path => 'node_modules/react-native-i18n'`

The code line must to be:
`pod 'RNI18n', :path => '../node_modules/react-native-i18n'`
because Podfile is placed in the `ios` folder.

**Comment by zoontek** [comment]
Fixed, thanks.
