### ISSUE TITLE
can't see Hebrew in real devices

### ISSUE THREAD

**Issue by assafb81** [AlexanderZaytsev/react-native-i18n#109]
Hi,
I am using react-native-i18n and I want to check support for Hebrew/Arabic.
in the emulators I can see Hebrew and Arabic but in real devices (iPad/Tablet) I can't see Hebrew.

I've tried to define Hebrew locale in my project as: 
1.'heb'
2. 'he'
3. 'he-il' / 'he-IL'
4 'he_il'/ 'he_IL'

but with no luck, any suggestions?

**Comment by assafb81** [comment]
Partial solution:
in Android (Nexus 10 - 5.1.1) for Hebrew the locale is 'iw-IL'

this does not work in iOS and I am not sure if it working on other Android versions.

**Comment by zoontek** [comment]
@assafb81 Check the lists of supported locales by platforms.
This lib only allow translations of text strings. For RTL support, check https://github.com/facebook/react-native/blob/master/Libraries/ReactNative/I18nManager.js

**Comment by assafb81** [comment]
Thanks for the reply, I will check that.
I mentioned the CSS layout because on emulators (Xcode, Android Studio) the layout changed accordingly and it still happen with a real Android device (Nexus 10 - 5.1.1, tablet) but not on real iOS device.
