### ISSUE TITLE
How to localise text with links?

### ISSUE THREAD

**Issue by ranyefet** [AlexanderZaytsev/react-native-i18n#11]
Hi, thanks for the great lib.

One of my texts in the app is:
```
{
  en: {
    termsOfUseText: "By click Submit you agree to Terms of Use and Privacy Policy"
  }
}
```
I need to have ```Terms of Service``` and ```Privacy Policy``` Links that open WebView.

I don't want to separate it into separate keys because it harder to translate and in some language the order of words can change so I need to allow the translators to translate it as a whole line.

Any suggestions on how to implement that? 

Thanks,
Ran.

**Comment by horatiua** [comment]
Hi,

I imagine that you can use a sprintf equivalent for JavaScript (https://www.npmjs.com/package/sprintf-js).
I imagine something like this: 
```
sprintf(
  'By` click Submit you agree to %s and %s', 
  '<a href="">' + I18n.t('Terms of Service') + '</a>', 
  '<a href="">' + I18n.t('Privacy Policy') + '</a>'
)
```
An npm package that could be helpful:
https://www.npmjs.com/package/sprintf-js
