### ISSUE TITLE
Check if key exists

### ISSUE THREAD

**Issue by RUIFERNANDE5** [AlexanderZaytsev/react-native-i18n#110]
Is there any available method to check if a key exists in the current language?
Currently if a key doesn't exist it returns a [missing "foo" translation], which I don't think its ideal.

**Comment by zoontek** [comment]
You can use the in operator. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in

```js
import en from './locales/en'

if ('key' in en) {
  // do something
}
```
