### ISSUE TITLE
Tranlation with an ellipsis doesn't work

### ISSUE THREAD

**Issue by XavierColombel** [AlexanderZaytsev/react-native-i18n#111]
When I translate a string containing an ellipsis (...), it tells me "missing translation". Any idea?

**Comment by zoontek** [comment]
@XavierColombel Can you provide the complete sentence? Also, try asking on https://github.com/fnando/i18n-js instead, this is not really a problem linked to the react-native provider...

**Comment by XavierColombel** [comment]
Sorry @zoontek, I forgot to precise I understood a key could not contain a dot, so I removed all dots in each key and it was OK.
