### ISSUE TITLE
Can I use react-native-i18n with react-native-web-boilerplate

### ISSUE THREAD

**Issue by ableabhijeet** [AlexanderZaytsev/react-native-i18n#112]
Hi,
Can I use react-native-i18n library with [react-native-web-boilerplate](https://github.com/agrcrobles/react-native-web-boilerplate)?
I was trying my luck with react-native-i18n library but react-native-18n import fails, RNI18n object returned as undefined.
`import I18n from 'react-native-i18n'`

Any suggestions?

**Comment by zoontek** [comment]
@ableabhijeet Looks like a link problem. Try doing a manual link following the documentation. https://github.com/AlexanderZaytsev/react-native-i18n#installation

**Comment by zoontek** [comment]
@ableabhijeet Correction: react-native-web-boilerplate is for browsers, and this package is not designed for that
