### ISSUE TITLE
Add more fallbacks relations

### ISSUE THREAD

**Issue by PolGuixe** [AlexanderZaytsev/react-native-i18n#113]
How can I add more fallback relations e.g. I want `en-US` and `en-GB` to fallback to `en`, but I want `ca` to fallback to `es`.

**Comment by zoontek** [comment]
@PolGuixe That's not really fallbacks if it's for a different language.
You have to initialize the lib differently, do a manuel test. Check the main file: https://github.com/AlexanderZaytsev/react-native-i18n/blob/master/index.js
