### ISSUE TITLE
manually set a language 

### ISSUE THREAD

**Issue by alainib** [AlexanderZaytsev/react-native-i18n#115]
I didn't use this plugin yet but i didn't see how to manually choose a language. 

For example i will make a list of country flag, the user click on one and this will set the choosen language  for translate. 
I can't just use the phone language because a lot of your users have english phone's but speaks other languages like spanish, portugish or french... etc

Is there a way to have a setter like `setLanguages('es')` or `setLanguages('fr')`  like the `getLanguages()` method ?

I didn't find this in the issues, sorry if already talk about it.

**Comment by alainib** [comment]
noobs inside sorry 

https://github.com/AlexanderZaytsev/react-native-i18n/issues/45

**Comment by ramsanath** [comment]
Were you able to find the solution?
