### ISSUE TITLE
My project is not building on android when using the newest version of react-native

### ISSUE THREAD

**Issue by nromptea42** [AlexanderZaytsev/react-native-i18n#117]
### Issue Description

I just got this error when trying to upgrade my project to react-native 0.47.1 and build on android

`node_modules/react-native-i18n/android/src/main/java/com/AlexanderZaytsev/RNI18n/RNI18nPackage.java:20: error: method does not override or implement a method from a supertype
  @Override
  ^`
### Steps to Reproduce / Code Snippets / Screenshots

In RNI18nPackage.java,
`@Override
  public List<Class<? extends JavaScriptModule>> createJSModules() {
    return Collections.emptyList();
  }`
I removed the `@Overrride` and it worked

### Environment
* React Native version: 0.47.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device on Android 7.1.2

**Comment by zoontek** [comment]
@nromptea42 Thanks. I just made a new release: https://github.com/AlexanderZaytsev/react-native-i18n/releases/tag/v2.0.4
