### ISSUE TITLE
bug, cannot read property 'languages' of undefined

### ISSUE THREAD

**Issue by jhon3rick** [AlexanderZaytsev/react-native-i18n#118]
Hi, I work on react 16.0.0-alpha.6 and RN 0.43.4 in IOS; And I have the error "can not read property 'languages' of undefined", and tried to install RNi18n by the react-native link command, cocoapod and manually but it always throws me the same error.

regards

**Comment by sospedra** [comment]
I faced the same problem. From my research I found that this piece of code is the one messing everything up: https://github.com/AlexanderZaytsev/react-native-i18n/blob/master/index.js#L7 

`RNI18n.languages` doesn't exists, hence, trying to access the `0` position blows up.
Instead, RNI18n has a `locale` attribute with the languages. 

I tried to manually change this line by:
`I18n.locale = RNI18n.locale.en;`

And everything worked as expected. 
Tho, I don't have proper knwoledge to suggest this is the solution I'm pretty sure is in this line.

Hope it helps ;)

**Comment by zoontek** [comment]
@sospedra The current version doesn't export any locale constant. Can you check the `ios/RNI18n.m` file in your `node_modules` directory?

**Comment by zoontek** [comment]
Did you upgrade from version 1.x?
Try cleaning your differents builds / cache.

`react-native unlink react-native-i18n` (check if it has been done, do a manually unlink if needed)
`rm -rf node_modules`
`yarn cache clean && npm cache clean`
`yarn`

Uninstall the app from your simulators / your devices

**On Xcode**
Product > Clean
Product > Clean build folder (click on Product with the option key pressed)

`rm -rf ~/Library/Developer/Xcode/DerivedData`
`cd android && ./gradlew clean`

`react-native link react-native-i18n`

Build! :)

**Comment by squgeim** [comment]
I followed the instructions and cleaned all the builds and caches. I sill have the same issue.

**Comment by zoontek** [comment]
@squgeim It might be a linking error. What `console.log(RNI18n)` gives you?

**Comment by squgeim** [comment]
@zoontek I removed the project and cloned it again. The problem seems to have fixed itself.

**Comment by zoontek** [comment]
I published the 2.0.5 release with a test in the /example folder: https://github.com/AlexanderZaytsev/react-native-i18n/tree/master/example/src

**Comment by rom1k** [comment]
I have this exact problem on ios after upgrading react native. Did anyone find a solution?

**Comment by jhon3rick** [comment]
I solved delete folder node_modules, command npm install and install for
command pod install

When delete node_modules and install every run pod install
