### ISSUE TITLE
Undefined is not an object (evaluating 'RNI18n.languages')

### ISSUE THREAD

**Issue by OverVlad** [AlexanderZaytsev/react-native-i18n#125]
I have this problem only when using EXPO (ios, android). When building with Xcode - don't have this problem.

Error in this line
`I18nJs.locale = RNI18n.languages[0];`
`export const getLanguages = RNI18n.getLanguages;`

I commented this lines and add `I18nJs.locale = 'en';` this help but not resolves the issue.

I used react-native default pack and add EXPO

**Comment by tamer316** [comment]
Happens to me as well, works fine on iOS but fails in Android, I followed the Android setup guide to no avail

**Comment by fmoessle** [comment]
same problem here, works on ios but not on android.

**Comment by gabrielmadruga** [comment]
Same here using expo.

**Comment by Dragsbaek** [comment]
+1

**Comment by OverVlad** [comment]
#126

**Comment by zoontek** [comment]
If you are using Expo, please consider using getCurrentLocaleAsync() and the i18n of your choice (i18n-js if you want, but you can use them all :)!) https://docs.expo.io/versions/latest/sdk/util.html

**Comment by alburdette619** [comment]
I am not using Expo at all and attempting to update to RN 48.1 I get this error as well.

**Comment by wangxiaoleiAI** [comment]
in your project
```$ react-native link```
and reboot

**Comment by blairvanderhoof** [comment]
I'm getting "Cannot read property 'getLanguages' of undefined. Steps I followed:

1. yarn add react-native-i18n
2. react-native link react-native-i18n
3. Run in XCode
4. See error
5. Using React Native 0.47.1

**Comment by blairvanderhoof** [comment]
It appears that the react-native link does not work, even though the console says it did. I had to add the project to Libraries then add the .a file in build phases, then it worked.

**Comment by zoontek** [comment]
I add a warning to warn the user when the package is not properly linked: https://github.com/AlexanderZaytsev/react-native-i18n/blob/master/index.js#L9

**Comment by JulioOrellana** [comment]
@blairvanderhoof you need to close the simulator, stop npm packager (npm start) and start all over. When you link something, a reboot is necesary so dependencies can load properly.

**Comment by chrisenabled** [comment]
I updated the dependencies with npm-check-updates -u; npm install && npm install --only=dev and then i had the same problem. How i solved it was to combine the series of suggestions. First unlink and then link again 

$react-native unlink react-native-i18n 
$react-native link

then stop and restart the react packager

**Comment by thanhppm** [comment]
I have an error in my project with RN 0.49.5 
http://prntscr.com/hbiw6i
Any one help me fix that issue? 
Thanks

**Comment by muei** [comment]
Closed why ? There are so many pepole, not one!

**Comment by JulioOrellana** [comment]
People please! when you link a new library in react native, you MUST stop your npm packager (the console with `npm start`). You must restart your npm start and run react-native run-ios o react-native run-android again! I had the same problem and that was the problem, the library was linked but you must restart your packager so the library can start working.

**Comment by zoontek** [comment]
@muei Because the solutions has already been given multiples times, and the documentation now reflect the current version changes.
