### ISSUE TITLE
Coexisting i18n implementation

### ISSUE THREAD

**Issue by felixus95** [AlexanderZaytsev/react-native-i18n#127]
Following scenario:

We have a main react-native project which is the logical part of the App. Most of our strings are defined within this project and we are using your package for i18n. On it's own it's working really nice.

We also have a second RN project which we are loading over the node modules into the first. We want to use your package in this project too, but when we do so only the strings of the second project are displayed right, while the main projects strings show the " missing en.xxx translation" error. 

Are we doing something wrong? On their own the implementation is working fine, but as soon as both are coexisting in the same App said problems are evolving.

Thanks in advance

**Comment by zoontek** [comment]
You can't do that with i18n-js because you can't have multiples instances of the global object.

**Comment by felixus95** [comment]
Ah! That’s the reason behind it. 

We created a third module to manage the translations. The other two can access the object this way. Works just fine.
