### ISSUE TITLE
How to pass variables

### ISSUE THREAD

**Issue by JulioOrellana** [AlexanderZaytsev/react-native-i18n#132]
I have i18n file

```
en.js
{
  hello: "Hello
}
....

app.js

I18n.t('hello')
```

In rails you can pass variables like

```
en.js
{
  hello: "Hello, %name"
}
....
app.js

I18n.t('hello', name: 'SomeDude') 

Output:

Hello SomeDude
```

Is there any way I can do this in react native? I have tried `I18n.t('hello',{ name: 'SomeDude' })` but this is not working :/.

Thanks in advance!

**Comment by JulioOrellana** [comment]
NVM, instead of doing `%name`, documentation says it must be do as `{{name}}`

**Comment by gianpaj** [comment]
thanks @JulioOrellana this should be documented in the README file

**Comment by gabrielew** [comment]
I have to use {{name}}
