### ISSUE TITLE
Cannot read property 'getLanguages' of undefined 

### ISSUE THREAD

**Issue by SvetoslavSlavov** [AlexanderZaytsev/react-native-i18n#134]
My code is from the demo
```
import React, { Component } from 'react';
import {
    Text
} from 'react-native';
import I18n from 'react-native-i18n';

class Demo extends React.Component {
    render() {
    return (
      <Text>{I18n.t('greeting')}</Text>
    );
  }
}

// Enable fallbacks if you want `en-US` and `en-GB` to fallback to `en`
I18n.fallbacks = true;

I18n.translations = {
  en: {
    greeting: 'Hi!'
  },
  fr: {
    greeting: 'Bonjour!'
  }
};

export default Demo;
```
I am getting 
![simulator screen shot - iphone 6s - 2017-10-11 at 19 40 40](https://user-images.githubusercontent.com/16868443/31453906-6638dd3e-aebc-11e7-971d-17de2e1272ea.png)
Thank you in advance! :)

**Comment by andrespch** [comment]
I think you need to install `react-native-i18n` as well as `ex-react-native-i18n`

**Comment by zoontek** [comment]
@SvetoslavSlavov Is the package correctly linked?

**Comment by stefanedberg** [comment]
I got this error when I forgot to restart the app after installing and linking the package. Solved by running again.

**Comment by kartiikeyabaleneni** [comment]
It Worked perfectly for a long time.I'm experiencing g this error suddenly. How to resolve this
