### ISSUE TITLE
Ejected app weird behavior

### ISSUE THREAD

**Issue by andrespch** [AlexanderZaytsev/react-native-i18n#135]
Hey there, first off thanks a lot for sharing this code.

I'm having issues testing the sample code after bundling my RN app and testing it from xcode.

I'm testing this method 

```js
async componentWillMount() {
    this.setState({ extraText: "will start" });

    const [dummy] = await Promise.all([I18n.initAsync()]);

    this.setState({ extraText: "I18n.initAsync() done" });
    const [deviceCountry] = await Promise.all([
      Expo.Util.getCurrentDeviceCountryAsync()
    ]);

    this.setState({ extraText: "getCurrentDeviceCountryAsync() done" });

    const [currentTimeZone] = await Promise.all([
      Expo.Util.getCurrentTimeZoneAsync()
    ]);

    this.setState({ extraText: "getCurrentTimeZoneAsync() done" });

    this.setState({ appIsReady: true }); // when all above promises above are resolved
  }
```

by cheking `this.state.extraText` I can tell that those sync calls never return, which defeats in my case the purpose of this strategy. Any ideas on why this is behaving different on the xcode app that loads the `jsbundle` than on Expo? 

Thanks in advance

**Comment by zoontek** [comment]
Did you eject with pure react-native or expokit?

**Comment by andrespch** [comment]
So I ejected this normally without Expokit, since I need to generate a bundle, in the end I understood that I can't use Expo after ejecting, which was kind of obvious.
