### ISSUE TITLE
iOs crashes

### ISSUE THREAD

**Issue by enguerranws** [AlexanderZaytsev/react-native-i18n#136]
Hi,

When I run my app in dev, everything works fine. However, when I turn it to release, the app crash with this log:

```
<Error>: *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Requiring unknown module "./locale/fr-FR".', reason: 'Unhandled JS Exception: Requiring unknown module "./locale/fr-FR".
```

I don't know where this module is required and why it doesn't work with a release build. Any ideas?

**Comment by nicksmetBagaar** [comment]
Had the same problem, traced it down to this line 

> moment.locale(I18n.locale);

Didn't give any warnings or errors until build for production. Hope it helps you out.

**Comment by kyo504** [comment]
I had the same problem after updating moment-related packages. 

- moment : 2.19.1 => 2.19.2
- moment-timezone : 0.5.13 => 0.5.14

I don't know what the problem is exactly but after downgrading versions it works fine. Hope this helps you.

**Comment by enguerranws** [comment]
Well, my issue was indeed related to moment.js, I wrongly assumed it was coming from `react-native-i18n`.

**Comment by hugoh1995** [comment]
Ok so how did you guys solved this?
