### ISSUE TITLE
Not able to use with new Android Studio 3.0

### ISSUE THREAD

**Issue by githubdoramon** [AlexanderZaytsev/react-native-i18n#141]
I have updated Android Studio to 3.0, react to 16, and react native to 0.49, and after all of that, I can't even sync the project in Android Studio anymore.

Any hints?

Here is the error

![image](https://user-images.githubusercontent.com/8230135/32244758-8d7281ec-be71-11e7-9c66-290acd5c0799.png)

**Comment by githubdoramon** [comment]
Anyone?

**Comment by wellingtoncabral** [comment]
Try to change react-native to 0.50.1. It worked here.

**Comment by githubdoramon** [comment]
No good here :(

**Comment by zoontek** [comment]
@githubdoramon Have you update to Android Studio 3.0.1? I encounter the same problem with multiples libs

**Comment by githubdoramon** [comment]
Same problem with 3.0.1 @zoontek 

@AlexanderZaytsev any tips?

**Comment by sibelius** [comment]
add this to build.gradle to handle new android build tools version

```gradle
ext {
    compileSdkVersion = 26
    buildToolsVersion = '26.0.2'
}

subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}
```

this is not related to this package
