### ISSUE TITLE
Date formating doesn't work with I18n.l(...)

### ISSUE THREAD

**Issue by zygama** [AlexanderZaytsev/react-native-i18n#145]
Hello everyone,

first I want to thank you for all the good work! :)

Here is my problem, I'm trying to format a date in my project which is a firebase timestamp, it didn't work, so I tried with the example in the doc which is:

`I18n.l("date.formats.ordinal_day", "2009-09-18", { day: '18th' }); // Sep 18th`
`I18n.translations["en"] = {
  date: {
    formats: {
      ordinal_day: "%B %{day}"
    }
  }
}`

I translated it to my use case with this : 
`I18n.l('profile_tab.profile_config.member_since', '2009-09-18', { day: '18th' } )`
`"profile_tab": {
    "profile_config": {
        "member_since": "%B %{day}"
    }`

but it prints me '2009-09-18' or it should be 'September 18th'.

Note: my translates are in a .json file 

If i'm missing something please help me..
Thank you :)

**Comment by zoontek** [comment]
@zygama It looks more of a i18n-js error than of this connector. Try publishing this issue on their project repo, people should be able to help more quickly :)

**Comment by rborn** [comment]
@zygama I always use moment.js for this
