### ISSUE TITLE
ios: appstore doesn't show localizations

### ISSUE THREAD

**Issue by tonygentilcore** [AlexanderZaytsev/react-native-i18n#148]
When I upload my localized react-native-i18n project to the appstore, it doesn't recognize the localizations. It seems I need to do some manual config in the xcode project as per the README. However, when I click to add a localization, I get a blank list of resources and the locale isn't actually added when I finish.

<img width="730" alt="screen shot 2017-11-27 at 4 31 57 pm" src="https://user-images.githubusercontent.com/1731736/33296469-ba3ab9fe-d390-11e7-8335-f28ffadf551f.png">

I'm sure I'm missing a step, any help would be warmly appreciated.

**Comment by zoontek** [comment]
@tonygentilcore Hi, can you provides a screenshot of your Project Infos? (similar to the one in the README)

**Comment by tonygentilcore** [comment]
@zoontek Thanks for getting back to me! Here's a screenshot. I suspect the root issue is that there are "0 Files Localized," but given everything non-trivial about this project is in RN, I'm not sure what I can/should choose to localize in Xcode (or exactly how, really).

<img width="696" alt="screen shot 2017-12-02 at 9 10 32 am" src="https://user-images.githubusercontent.com/1731736/33517898-f677389e-d740-11e7-9c7b-28071d227c9d.png">

Thanks again for taking the time to help.

**Comment by zoontek** [comment]
Even if you are not using it, try adding a new locale, and translate your Info.plist: https://stackoverflow.com/a/25736915

You can keep the InfoPlist.strings blank.

**Comment by tonygentilcore** [comment]
That was exactly it. Thanks again.
