### ISSUE TITLE
How to use from Java code?

### ISSUE THREAD

**Issue by plaa** [AlexanderZaytsev/react-native-i18n#150]
We're using react-native-i18n for our project localization.  I now need to fetch a localization string from Java code for `Toast.makeText`.  How can this be done?  I couldn't find any instructions anywhere.

**Comment by zoontek** [comment]
Form React-native documentation:

```js
ToastAndroid.show(t('translation_key'), ToastAndroid.SHORT);
```

https://facebook.github.io/react-native/docs/toastandroid.html

**Comment by plaa** [comment]
I'm not trying to generate a toast from react code, I'm trying to generate it from native Android Java code.  How can I get a localization string from within Java code?

**Comment by zoontek** [comment]
You can't do JS -> Java, only expose native module to JS.
