### ISSUE TITLE
Cannot read property 'getLanguages' of undefined

### ISSUE THREAD

**Issue by julestruong** [AlexanderZaytsev/react-native-i18n#152]
Hello guys, i've got this wonderful lib and it works fine except during test

I'm using jest, and i've go this weird error.
```
    TypeError: Cannot read property 'getLanguages' of undefined

      at Object.<anonymous> (node_modules/react-native-i18n/index.js:12:45)
      at Object.<anonymous> (src/i18n/index.js:1:849)
      at Object.<anonymous> (src/features/login/index.js:5:11)
```

The app works tho.

@AlexanderZaytsev

**Comment by wilomgfx** [comment]
Same here, one every two runs.

**Comment by yanivnizry** [comment]
+1

**Comment by giantss** [comment]
+1

**Comment by giantss** [comment]
![image](https://user-images.githubusercontent.com/13778798/33830128-e0774b32-dead-11e7-86c2-a7a7756fd8bc.png)
Why does this happen?
@AlexanderZaytsev

**Comment by zoontek** [comment]
@giantss Try replacing the function with (don't forget to clean the packager cache):

```js
export const getLanguages = () => RNI18n.getLanguages()
```

Does it fixes the problem?

**Comment by LcTwisk** [comment]
+1

**Comment by giantss** [comment]
@zoontek thanks!  It works.

**Comment by dccarmo** [comment]
@zoontek Fix works, but it gives a warning when testing: 
```
console.warn node_modules/react-native-i18n/index.js:9
      react-native-i18n module is not correctly linked
```

**Comment by giantss** [comment]
#153

**Comment by zoontek** [comment]
@giantss What version of RN are you using?

**Comment by giantss** [comment]
@zoontek 0.49.5

**Comment by compojoom** [comment]
@zoontek - with your change it's working. I guess we need a pull request :)

**Comment by zoontek** [comment]
@compojoom feel free to do it :)

**Comment by compojoom** [comment]
@zoontek - I see that we already have one.

**Comment by zoontek** [comment]
New version is out https://github.com/AlexanderZaytsev/react-native-i18n/releases/tag/v2.1.0 !
