### ISSUE TITLE
month names doesn't change when I change the language

### ISSUE THREAD

**Issue by jose4125** [AlexanderZaytsev/react-native-i18n#154]
in ios when I change the language inside the general settings (Language & Region) the month name in the app doesn't change from en to es.

I tried with
I18n.strftime(newDate, '%b %d')

I expected in en
Aug 09

and in es
Ago 09

how can I do that?

**Comment by zoontek** [comment]
@jose4125 You need to add placeholders for date formatting:
See https://github.com/fnando/i18n-js#date-formatting & https://github.com/fnando/i18n-js/blob/master/spec/js/translations.js#L79 for docs and an example
