### ISSUE TITLE
How does it manage placeholders?

### ISSUE THREAD

**Issue by MyaElla** [AlexanderZaytsev/react-native-i18n#155]
In locale json 
`"about":{
        "title": "Additional screen_GB",
        "info": "Information:_GB",
        "explanation": "This screen uses no {{name}} and is not connected to the ..._GB"
      },
      "app": {
        "name": "Some App",
        "example": "stuff"
      }`
And in view 
`{I18n.t('about.explanation', { name: 'app.name' })}`

**Comment by zoontek** [comment]
@MyaElla Just follow the i18n-js doc https://github.com/fnando/i18n-js/blob/master/README.md :)
