### ISSUE TITLE
when run  'react-native link' ,err for this.

### ISSUE THREAD

**Issue by believeZJP** [AlexanderZaytsev/react-native-i18n#156]
$ react-native link
Scanning folders for symlinks in E:\code\companyProjects\ablecloud-universal-app\node_modules (62ms)
rnpm-install info Linking react-native-i18n android dependency
rnpm-install info Android module react-native-i18n has been successfully linked
rnpm-install info Linking react-native-i18n ios dependency
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'match' of undefined
Please file an issue here: https://github.com/facebook/react-native/issues

**Comment by zoontek** [comment]
There are already one: https://github.com/facebook/react-native/issues/16774

**Comment by sibelius** [comment]
we can close this, not related to this package
