### ISSUE TITLE
Error linking / importing RNI18n

### ISSUE THREAD

**Issue by BrettBukowski** [AlexanderZaytsev/react-native-i18n#158]
Reopening #149 (and #114 and #130) as the same problem is still happening, just with a different error message, after the #153 fix.

Steps:

(following the setup instructions from the readme)

React Native - 0.37.0
Xcode 9.2

1. `npm install react-native-i18n --save` (which is now the latest release, 2.0.10)
2. `react-native link`
3. `react-native run-ios`
4. Import a file in your project that contains:

```javascript
import I18n from 'react-native-i18n';

I18n.getLanguages().then((langs) => console.log(langs));
```

-> `I18n.getLanguages is not a function`

**Comment by sibelius** [comment]
if this is `undefined` https://github.com/AlexanderZaytsev/react-native-i18n/blob/master/index.js#L3

the link is wrong

**Comment by zoontek** [comment]
Looks like a linking problem again.

**Comment by BrettBukowski** [comment]
Thanks for investigating @zoontek - The import is like `import I18n from 'react-native-i18n';`

**Comment by zoontek** [comment]
@BrettBukowski Ok, can you try:

```js
import { NativeModules } from 'react-native';
console.log(NativeModules.RNI18n);
```

And reply what it returns?

**Comment by ansonyao** [comment]
I had the same problem with 2.0.10. You can try install 2.0.9.

Then use this

```
import I18n, { getLanguages } from 'react-native-i18n';
getLanguages().then((langs) => console.log(langs));
```

It works for me

**Comment by ansonyao** [comment]
@BrettBukowski 
I think it is the syntax for importing.

It should be: 
```

import I18n, { getLanguages } from 'react-native-i18n';
getLanguages().then((langs) => console.log(langs)); 
```

**Comment by zoontek** [comment]
@ansonyao Well see! I didn't notice the error in the import.
I will make a PR to supports both syntax.

**Comment by zoontek** [comment]
New version is out: https://github.com/AlexanderZaytsev/react-native-i18n/releases/tag/v2.0.11

**Comment by dernise** [comment]
Doing this makes all the values inside the module read-only in ES6 since exported values are now constants. Therefore, this code isn't correct in ES6:

```
import I18n from 'react-native-i18n'
I18n.fallbacks = true
I18n.translations = {
    en: en,
    fr: fr,
}

```
since fallbacks and translations are now read-only. Please either create setters or revert this change.
