### ISSUE TITLE
i18n lint

### ISSUE THREAD

**Issue by sibelius** [AlexanderZaytsev/react-native-i18n#159]
is there any way to "`lint`" the codebase

so we can make sure there is no wrong i18n.t calls?

maybe we can make flowtype handle this check for us

any thoughts on this @calebmer?

**Comment by cem2ran** [comment]
Yes! I'm already doing this actually. 

![kapture 2018-01-10 at 18 23 08](https://user-images.githubusercontent.com/959142/34786135-7e6247ba-f633-11e7-9a00-000be51e48e7.gif)

Here my entrypoint for my translations:
```javascript
import I18n from 'react-native-i18n';
import en from './en.js';
import da from './da.js';

I18n.fallbacks = true;

const translations: {[key: string]: typeof en & $Shape<typeof en>} = {
  en,
  da,
};

I18n.translations = translations;

const t = (key: $Keys<typeof en>, ops: Object = {}): string => I18n.t(key, ops);

module.exports = {
  t,
  // export keys so you can do `import {commentPlaceholder} from 'i18n'`;
  ...Object.keys(en).reduce((strings, key) => ({...strings, [key]: t(key)}), {
  }),
};
```

`en.js` and `da.js` are simply:
```javascript
//@flow
//prettier-ignore
export default {
  commentPlaceholder: 'Say something nice...',
  ...
}
```

The check goes both ways, if en.js or da.js are out of sync with eachother w.r.t keys:
![image](https://user-images.githubusercontent.com/959142/34785840-9c857f74-f632-11e7-978c-487e9a48c064.png)

IDE's like intellij and webstorm even give you completions!

**Comment by sibelius** [comment]
I think we can provide a react-native-i18n typedef that handle this for us

**Comment by sibelius** [comment]
awesome @cem2ran 

tks

you could send this to flow-typed and ask for help there
