### ISSUE TITLE
React pod dependency breaks module resolution.

### ISSUE THREAD

**Issue by plevetsky** [AlexanderZaytsev/react-native-i18n#160]
RNI18n.podspec includes "React" as a dependency.  The React pod is deprecated, and including it as a dependency results in errors such as:

`Ambiguous resolution: module '/AwesomeProject/index.js' tries to require 'react-native', but there are several files providing this module.`

**Comment by zoontek** [comment]
@plevetsky If you use Cocoapods, you are supposed to include React this way: https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
