### ISSUE TITLE
getLanguages() returns garbage

### ISSUE THREAD

**Issue by michaelfranz** [AlexanderZaytsev/react-native-i18n#164]
**react-native-i18n V2.0.10**

Running getLanguages() on iOS in the simulator and on my iPhone returns the following:
{"_40":0,"_65":0,"_55":null,"_72":null}

What might be causing this?

[Update: Noob error. Incorrect usage. Correct usage is: getLanguage().then(...)]

**Comment by zoontek** [comment]
@michaelfranz It's not garbage, it's called a Promise: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

Please consider closing issues like this by yourself, open source is a community! :)
