### ISSUE TITLE
Can't always find a country to generate a locale

### ISSUE THREAD

**Issue by samueljseay** [AlexanderZaytsev/react-native-i18n#165]
We get quite a few of our users marked as having a locale of just "en" in Android because it appears that `locale.getCountry()` is [not a sufficient solution for all countries](https://stackoverflow.com/questions/3659809/where-am-i-get-country)

I'm wondering if something more comprehensive like [this solution](https://stackoverflow.com/a/19415296/472987) might be considered an acceptable PR?

PS: Thanks so much for making this wonderful library, it has been so useful to us!

**Comment by zoontek** [comment]
@samueljseay The language (and country variation) of the device is not really the same as the country where the user is currently.

An example with me: My phone is configured with en-US, but I live in France, and I don't want en-FR translation. Check solutions like https://github.com/pocesar/react-native-sim-data :)

**Comment by samueljseay** [comment]
Thanks @zoontek I'll look in to it. Appreciate the advice!
