### ISSUE TITLE
Package install React@0.11.0

### ISSUE THREAD

**Issue by kukko** [AlexanderZaytsev/react-native-i18n#167]
After installed `react-native-i18n` package, Cocoapods install `React@0.11.0` which is a little bit old.

I made the following steps:
```
npm install react-native-i18n --save
react-native link
cd iOS
pod install
```

When Cocoapods installing the dependencies, it's Install `React@0.11.0` and because of that, when I run the App, I get a LinkedStateMixin exception. There is any way how this package don't install older version of `React`?

**Comment by zoontek** [comment]
You need to use React from node_modules. Check the official documentation: https://facebook.github.io/react-native/docs/integration-with-existing-apps.html
