### ISSUE TITLE
load language from server then re-render?

### ISSUE THREAD

**Issue by 1c7** [AlexanderZaytsev/react-native-i18n#168]
I have 4 language store in local, en, tw, jp, zh.
![image](https://user-images.githubusercontent.com/1804755/35795752-1e0f41b2-0a95-11e8-8879-d6e9d956c7bf.png)

now I need support Russian

I am loading `Russian` language by http request, and then
```
I18n.translations["ru-BY"] = output;
```
![screenshot_20180205-164329](https://user-images.githubusercontent.com/1804755/35795532-64d29ad2-0a94-11e8-9b78-46c8a8483eff.png)

and clearly it need re-render to make it work.

## I know this is not exactly `react-native-i18n` issue, 
I need looking for a way to re-render the app.
I just thought maybe ask here and somebody know the answer
:smile:

I have tried 
* `react-native-restart` not working, it's restart, not re-render, it just restart.
* `forceUpdate()` not working
* https://blog.callstack.io/react-native-handling-language-changes-on-android-the-right-way-c883056a8f5c  this one work, but only work change language setting in Android, and when switching to the app, app would reload and now language is right. but not what I need.

# Anyone know how to re-render the app once it done loading language from remote server?
Thanks!

**Comment by 1c7** [comment]
### I am using React Native 0.52 and develop for Android

**Comment by 1c7** [comment]
# my `react-native info` (if you want know more about my env)
![image](https://user-images.githubusercontent.com/1804755/35795874-a3b46568-0a95-11e8-83af-7a48d84eba0a.png)

**Comment by 1c7** [comment]
because I am using React Navigation, I thought about reset route to make it reload. and it kinda work.
https://github.com/react-navigation/react-navigation/issues/1990#issuecomment-332782092
https://reactnavigation.org/docs/navigation-actions.html#reset
I am still trying this, but so far it seem work.

would come back and update once I got some progress

**Comment by zoontek** [comment]
If you use https://github.com/react-community/react-native-languages and `i18next` + `react-i18next`, it is easy to rerender your app :)

**Comment by 1c7** [comment]
@zoontek Would try, Thank you!

**Comment by 1c7** [comment]
I would close this issue in 1-3 day, after my problem solved, 
and maybe put some note or useful code sample here too.
:smile:

**Comment by 1c7** [comment]
I wrote a little demo App, https://github.com/1c7/react-native-langauge-hot-reload-example

**Comment by zoontek** [comment]
@1c7 Awesome work, thanks you!

**Comment by 1c7** [comment]
:D

**Comment by 1c7** [comment]
it turns out that demo app I wrote is not working for loading language from the remote server.  
(the UI wouldn't refresh, even the `addResourceBundle` success, and I successfully add the Russian language)

it works for change language in the Android Setting. and switch back to App, it would work.  

anyway, eventually I use following code sample to make it work
```
export default translate('translation')(HomeScreen);
export default translate('translation')(LogsScreen);
export default translate('translation')(ProfileScreen);
```

**Comment by davidbilik** [comment]
@ic7 hey, I want to make the same thing - download new languages from server and make the app to use them - but I dont get your last message here. Where did you use that code? And dont you need to re-render whole app when you download new language that was not there before and user have the currant locale the same as the one right downloaded?

**Comment by 1c7** [comment]
@davidbilik 
Hi I use "translate" from i18next
```
import { translate } from 'react-i18next';
```

and then,
```
export default translate('translation')(More)
```

use the `translate` to wrap my component, exactly like your code there.

I think the problem is language code,
in my case, Russian is `RU-BY`, not just `ru`

you should try `console.log(i18n)` after the language is loaded.

and also print out current language code, see if they match.

hope it help.

**Comment by davidbilik** [comment]
@1c7 my server response looks like
```json
{
   "en" : { ... },
   "fr" : { ... }
}
```
but the language from the system (android) is `fr-FR`. You mean that the response from the server should have the `fr-FR` key? I have the project at home and I cant try it now :( Also, do you use that `i18nextProvider`or do you set the i18n instance to `translate` method yourself as I do above?

**Comment by 1c7** [comment]
@davidbilik 

1. you don't need to change the 'fr' key from the server, just use `fr-FR` when using `addResourceBundle`
maybe using an `if` statement like 

```
if(key == 'fr'){
   addResourceBundle( blah blah blah )
}
```

2. I use both `I18nextProvider ` and `translate` to make it work
The code example below is from my real project (Bitbucket private repo):

in root folder `App.js`, `MainScreen` is first one in StackNavigator
![image](https://user-images.githubusercontent.com/1804755/36661182-9acdebe6-1b15-11e8-8ab7-6be8f018b261.png)

and in `MainScreen` I use `react-native-tab-view` to make the bottom tab
so code look like this: 
![image](https://user-images.githubusercontent.com/1804755/36661314-e3f82dcc-1b15-11e8-903a-51fe8864ab7f.png)

inside `HomeScreen `
![image](https://user-images.githubusercontent.com/1804755/36661361-ffc9397e-1b15-11e8-8061-150f06546204.png)

![image](https://user-images.githubusercontent.com/1804755/36661344-f7734be8-1b15-11e8-9705-504da2b9205b.png)


hope it help

**Comment by 1c7** [comment]
if there are more question, feel free to ask, I would help as much as I can

**Comment by helloo0-0oword** [comment]
In the app I have a list of languages ​​when I select 1 in which whether the application changes the language in real time
@zoontek  @1c7  @davidbilik

**Comment by 1c7** [comment]
@helloo0-0oword I tried change language in real time.
no success. now I am not developing React Native anymore.
working on web app at the moment (Vue.js)

can't help. sorry.
good luck

**Comment by davidbilik** [comment]
@helloo0-0oword I have migrated to i18next after the read of this issue https://github.com/AlexanderZaytsev/react-native-i18n/issues/68
