### ISSUE TITLE
Return scope using a variable

### ISSUE THREAD

**Issue by dannstuff** [AlexanderZaytsev/react-native-i18n#169]
Hi everyone, I've set up a file called en.js with the following in - 

```js
    milestones: {
        Kickoff: 'Setup',
        Dossier: 'Property Information',
        Contract: 'Contract',
        Searches: 'Searches & Enquiries',
        Finance: 'Finance',
        Completion: 'Completion',
        PostCompletion: 'Post Completion',
    },
```

essentially, I need to pass my i18n.t a variable to return the string associated with any of these keys. An example would be if I wanted Kickoff i would use i18n.t(['milestones', 'Kickoff']) - if thats the case why cant I do -- 

key = 'Kickoff'
i18n.t(['milestones', key])

any help would be really useful, i've checked the documentation like 10 times over and cant work out a way of doing what I want, so if im doing something wrong or anyone has a way around it i'd be super greatful! (apologies if I haven't been very clear im quite new to this)

**Comment by Yarkhan** [comment]
You may do like so:

```
import I18n from 'react-native-i18n'

I18n.fallbacks = true
I18n.translations = {
  en: {
    Home: {
      conversations: 'Conversations'
    }
  },
  pt: {
    Home: {
      conversations: 'Conversas'
    }
  }
}

I18n.t('Home.conversations')
```
Refer to [i18n-js documentation](https://github.com/fnando/i18n-js#setting-up) for more info, as `react-native-i18n` wraps over it

**Comment by zoontek** [comment]
@Yarkhan is right, this package is just a wrapper :)
