### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by maxxdevHH** [AlexanderZaytsev/react-native-i18n#17]
Hey there,
i am not sure if I use the plugin in the correct architecture.

In my index.ios.js I call a component which includes the <NavigatorIOS/>
The Navigator calls another component (a login screen).

The i18n.t functions says ['missing en-US … translation']. (in the login component)
If I console.log() the I18n Object I can find every translations in the translations object. 

What goes wrong? Is there a function to re-init?

**Comment by ravitez** [comment]
@maxxdevHH  have the same issue here.Are you able to figure it out ?

**Comment by yray** [comment]
Same issue here,
I've tried updating it to newest tags and still no luck

**Comment by everyusernameistaken123** [comment]
+1
Putting this in my react-render-function:
```
<Text>
  {I18n.t('enter_user_name')}
  {I18n.translations.en.enter_user_name}
</Text>
```
results in:

> [missing "en.enter_user_name" translation]
> Enter user name (my translation)

I am using kind of the same architecture as maxxdevHH, i.e. having some imports and exports with the I18n-object.

**Comment by unicornRainbows** [comment]
Same issue here.. not constant. How can we help? :)

**Comment by kathyLA** [comment]
I have the same issue before, but turn out that i forget to import my directory where I am define the en file. also Then just using the I18n.t  then it will work 
Totally 2 import. one for the  en directory and another for the 'react-native-i18n'

**Comment by aceisScope** [comment]
I came across this issue because the key I used for a string is illegal. something like `name.text = 'name'` will result in a Missing Translation error.
