### ISSUE TITLE
React as a dependency in podspec

### ISSUE THREAD

**Issue by gaykov** [AlexanderZaytsev/react-native-i18n#170]
Hello,

Could you please explain the reason of having React as a dependency in your podspec file? First of all, it's installing the old version of react and gives a warning that React v11 is deprecated and also for me it breaks the build somehow (it breaks an integration of app-center library actually), but anyway, can't get a reason of having React as a dependency here.

**Comment by lucasfernandes** [comment]
I've tried this way and had a problem when a deprecated react version was installed.
I'm trying the manual installation.

**Comment by wzhou40555** [comment]
Hello,

I installed react-native-i18n today and having the same problem. What is the solution?

**Comment by zoontek** [comment]
You need to use the local version of `React` as pod dep, as explained in the doc: http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies

**Comment by gaykov** [comment]
@zoontek thank you for the answer! 

Why do we need to use it? The point of the issue is that when you install `react-native-i18n` it breaks a build by adding React as a dependency. And as I see it's not necessary here (please correct me if I'm wrong).

**Comment by zoontek** [comment]
Yes, it's not necessary for this lib I think, but it might be necessary if you manage your others deps with Cocoapods :)

I could remove it, but I need a proper and clear explanation in the README.

**Comment by matheusrocha89** [comment]
@zoontek tried that but still have the same problem, duplicated React in my project and the package can't make the bundle

**Comment by SeanRyanMcVey** [comment]
add dependencies to your Podfile :
`pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n`
run pod install
