### ISSUE TITLE
Not correctly linked when used in tests

### ISSUE THREAD

**Issue by hjylewis** [AlexanderZaytsev/react-native-i18n#173]
`console.warn: react-native-i18n module is not correctly linked`

Can we change [this](https://github.com/AlexanderZaytsev/react-native-i18n/blob/master/index.js#L10...L12) to:
```
} else if (__DEV__ && !__TEST__) {
  console.warn('react-native-i18n module is not correctly linked');
}
```
or something like that?

**Comment by zoontek** [comment]
You need to mock native modules for testing. An example exist in /example

**Comment by hjylewis** [comment]
Awesome. Worked perfectly!

Maybe we should add a note in the readme about this?
