### ISSUE TITLE
react-native-i18n module is not correctly linked

### ISSUE THREAD

**Issue by gameunite** [AlexanderZaytsev/react-native-i18n#177]
Every time I run jest this error pops up

```
console.warn node_modules/react-native-i18n/index.js:14
    react-native-i18n module is not correctly linked
```

It works fine in both iOS and Android though. Any reason why it shows up?

**Comment by zoontek** [comment]
Does it work fine for english only?

**Comment by mnecchi-akkroo** [comment]
Same here.

```
console.warn node_modules/react-native-i18n/index.js:11
      react-native-i18n module is not correctly linked
```

Using version 2.0.12:

```
react-native-i18n@^2.0.12:
  version "2.0.12"
  resolved "https://registry.yarnpkg.com/react-native-i18n/-/react-native-i18n-2.0.12.tgz#4a503cc73b2fe55e8518f6d4a1340d3b449d8d1a"
  dependencies:
    i18n-js "^3.0.3"
```

**Comment by oferRounds** [comment]
+1

**Comment by rodalmeida** [comment]
#173

**Comment by rodalmeida** [comment]
Check issue #173
You have to mock every native module if you want to test it with jest

**Comment by zoontek** [comment]
Did you mock the module like https://github.com/AlexanderZaytsev/react-native-i18n/blob/master/example/src/__mocks__/react-native-i18n.js ?

**Comment by zedtux** [comment]
I have this warning when running the app (without any test framework). Is there anything I could do to fix it?

**Comment by AndrewHenderson** [comment]
@zoontek I did that, but it did not remove the warning.

**Comment by AndrewHenderson** [comment]
@zoontek I must be misunderstanding. Why would I mock `i18n-js`?

```js
import I18nJs from 'i18n-js';

I18nJs.locale = 'en'; // a locale from your available translations
export const getLanguages = (): Promise<string[]> => Promise.resolve(['en']);
export default I18nJs;
```

**Comment by zoontek** [comment]
@AndrewHenderson This package only get the language of the device and return an instance of i18n-js.

**Comment by vanGalilea** [comment]
Hi Guys!

This fixed the warning for me

Create a global mock for the library in the root of your project --> __mocks__/react-native-i18n.js
This will load the mock instead of the library when running the code under testing.

react-native-i18n.js should look like this

```
export default {}
```

For more info read this https://jestjs.io/docs/en/manual-mocks.html#mocking-node-modules

**Comment by martabacc** [comment]
your solution rendered all my snap test failed ._.

**Comment by johhansantana** [comment]
> Hi Guys!
> 
> This fixed the warning for me
> 
> Create a global mock for the library in the root of your project --> `__mocks__/react-native-i18n.js`
> This will load the mock instead of the library when running the code under testing.
> 
> react-native-i18n.js should look like this
> 
> ```
> export default {
>   t: jest.fn(()=> 'mocked translation')
> }
> ```
> 
> For more info read this https://jestjs.io/docs/en/manual-mocks.html#mocking-node-modules

this should work but for some reason I'm still getting 
```
Invariant Violation: Native module cannot be null.
```

**EDIT**
Seems like the error I'm getting is not related to this library but rather other stuff that was being used in my `utils` file where this library was being used with a custom helper we made:
```javascript
export const i18n = (key, params = {}) => I18n.t(key, params);
```

Moving this helper directly into the test file fixes the error.
