### ISSUE TITLE
Very weird results on iOS 9.3 

### ISSUE THREAD

**Issue by agolovenko** [AlexanderZaytsev/react-native-i18n#18]
My iPhone is configured to use en-US language but the region is Russia.

So here is what I get from objective-C:
```
[[NSBundle mainBundle] preferredLocalizations]; //= "en"
[NSLocale preferredLanguages]; //= en-US
NSLocalizedString(@"newPhrasebooksAvailable", nil); //returns an English-localized string from Localizable.strings

```

And this is what I get in JavaScript:
`console.log(require('react-native').NativeModules.RNI18n.locale, I18n.locale); // output is 'ru_RU', 'ru-RU'
`

I'm not sure when it started but maybe this wasn't the issue before iOS 9.3. Anyway, it is now.

**Comment by weixingsun** [comment]
@agolovenko Have you managed to solve this issue? So it means we should use language instead of locale ,right ?

**Comment by hstaudacher** [comment]
Same issue. In the simulator it returns the correct locale. But on the device I get the same wrong result as you @agolovenko

**Comment by hstaudacher** [comment]
I have a fix, it is in this Pull Request https://github.com/AlexanderZaytsev/react-native-i18n/pull/35
