### ISSUE TITLE
How to make the text bold ?

### ISSUE THREAD

**Issue by shaheem-khanzada** [AlexanderZaytsev/react-native-i18n#183]
alreadyDone : 'Vous avez déjà encaissé ce code le {{lockedDate}} à {{lockedTime}}.Le montant du code est de <Text>{{amount}}</Text> DH.' 

this is not working can you tell me the proper solution ?

**Comment by zoontek** [comment]
Use `<Text style={{fontWeight: 'bold'}}>{i18n.t('.....')}</Text>`

This has nothing to do with i18n, I'm closing this.
