### ISSUE TITLE
Not getting currency format from devices

### ISSUE THREAD

**Issue by diegosiao** [AlexanderZaytsev/react-native-i18n#187]
Hello there!

Should not the function **I18n.toCurrency(numberValue)** consider the default locale in order to format the number?

Although the **I18n.currentLocale()** is 'pt-BR' the currency is always formatted like USD ($3.45) instead of BRL (R$3,45).

Am I doing something wrong here or missed something?

Thanks in advance!

**Comment by derekbar90** [comment]
I'm also seeing this issue, @diegosiao did you have any luck?

**Comment by diegosiao** [comment]
Right. I am closing this issue.
