### ISSUE TITLE
Add fallback to Localizable.strings

### ISSUE THREAD

**Issue by agolovenko** [AlexanderZaytsev/react-native-i18n#19]
It's a feature request but I think it's quite important to be able to access resources that are translated in Localizable.strings already.

Should be something like if resource is missing in JavaScript then look for it Localizable.strings

**Comment by Victoor** [comment]
Try this:
```
I18n.defaultLocale = 'es';
I18n.fallbacks = true;
```

**Comment by yishus** [comment]
Hi! I'm running into the same problem. Would love to use react-native-i18n on a hybrid iOS app, and we have our localized files stored in Localizable.strings. How can I use those files and not have to redefine the translations in js?

For now I am getting the `[missing "en.this.string.key"]` error and the key I use in Localizable.strings is `this.string.key`
