### ISSUE TITLE
Import difference

### ISSUE THREAD

**Issue by DLevai94** [AlexanderZaytsev/react-native-i18n#196]
Hello!

What's the difference in the usage in components between these 2 imports?

`import I18n from 'react-native-i18n';`
or
`import I18n from '../i18n';`

both works perfectly.

Or are there any difference?

**Comment by zoontek** [comment]
`../i18n` is a relative import and depends on the project directories architecture. (You import the file named `i18n` from the parent directory.

`react-native-i18n` is a dependency import (You import `node_modules/react-native-i18n/index.js`)

**Comment by DLevai94** [comment]
Yes, I know it. But is there some performance or other difference?

**Comment by DLevai94** [comment]
```
import I18n from 'app/i18n/i18n';

class Demo extends React.Component {
  render () {
    return (
      <Text>{I18n.t('greeting')}</Text>
    )
  }
}
```

vs

```
import I18n from 'react-native-i18n';

class Demo extends React.Component {
  render () {
    return (
      <Text>{I18n.t('greeting')}</Text>
    )
  }
}
```
