### ISSUE TITLE
Execution failed for task ':react-native-i18n:verifyReleaseResources'

### ISSUE THREAD

**Issue by tregismoreira** [AlexanderZaytsev/react-native-i18n#197]
I'm trying to build a release version of my app but I'm getting this error:

```
* What went wrong:
Execution failed for task ':react-native-i18n:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```

I already checked the linked libraries, sdk version etc. Did anyone get this error before?

SDK version: 26
Build tools: 26.0.2

**Comment by Pianist038801** [comment]
same issue I found.

**Comment by twalopro** [comment]
This fix it for me

This usually happen when you are using different compileSDKVersion and BuildToolsVersion in my case    i have to change it in the react-native-i18n folder inside the node-modules

Go to node_modules/react-native-i18n/android/build.gradle

Edit the compileSDKVersion and BuildToolsVersion to merge yours in  /android/build.gradle

**Comment by gianpaj** [comment]
Another workaround is to add this in your root `build.grade` file:
```
subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}
```

**Comment by twalopro** [comment]
@gianpaj Thanks , That work better and also prevent touching the library files

**Comment by zoontek** [comment]
Should be fixed in the last version (allowing android SDK versions customization)

**Comment by gianpaj** [comment]
@zoontek I upgraded to 2.0.14 and removed the code above (`subprojects...`), but got the same error message.

I had to add it again to make a build. Note debug builds don't have this issue, only release builds.
