### ISSUE TITLE
Is there any way to set default translation when locale translation file not exist ?

### ISSUE THREAD

**Issue by tsaohucn** [AlexanderZaytsev/react-native-i18n#200]
For example, my phone locale setting is en, but my en.js file didn't exist, so I want to system pick a default.js when en.js didn't exist, how could I do ?

**Comment by zoontek** [comment]
@tsaohucn Referring to the i18n-js documentation, use `I18n.defaultLocale =`

https://github.com/fnando/i18n-js#setting-up
