### ISSUE TITLE
Build error Could not find method implementation() for arguments...

### ISSUE THREAD

**Issue by CptFabulouso** [AlexanderZaytsev/react-native-i18n#204]
I get gradle build error after upgrading libraries

```
* Where:
Build file '.../node_modules/react-native-i18n/android/build.gradle' line: 31

* What went wrong:
A problem occurred evaluating project ':react-native-I18n'.
> Could not find method implementation() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

package versions:
"react": "16.4.1"
"react-native": "0.56.0"
"react-native-i18n": "^2.0.14"

ext values in my project android/build.gradle
```
ext {
    buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
}
```

**Comment by CptFabulouso** [comment]
upgrading gradle helped, changes I made

/android/build.gradle
```
buildscript {
    repositories {
        jcenter()
        google() //added this
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1' //changed version

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
...
```

/android/gradle/wraper/gradle-wrapper.properties
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip //changed version
```

**Comment by GertjanReynaert** [comment]
Upgrading my gradle version to the same as yours causes an `aapt` crash when building my app 😕

**Comment by CptFabulouso** [comment]
I think the cause is some different library, I know it happened to me in some projects and only solution I found was disabling it by adding `android.enableAapt2=false` to android/gradle.properties

**Comment by CptFabulouso** [comment]
I misunderstood your issue, it happened to me during build project too. Found [this issue](https://github.com/react-community/create-react-native-app/issues/499) suggesting to add to android/build.gradle:
```
subprojects { 
     afterEvaluate { 
         project -> if (project.hasProperty("android")) { 
             android { 
                 compileSdkVersion 26 
                buildToolsVersion '26.0.2' 
             } 
         } 
     } 
 }
```
that worked for me, hope nothing broke in app

**Comment by 1fabiopereira** [comment]
I got this problem too :sad:

**Comment by hanssonfredrik** [comment]
This started to happen in my project as well. I am running 2.0.12 and suddenly the project does not build in AppCenter with the error mentioned in the first post. I have not made any change at all to my project...

**Comment by CptFabulouso** [comment]
I've created PR for this. I don't think users should be forced to bump their project gradle version, also when the docs don't mention it.

**Comment by jorgefspereira** [comment]
I had the same issue with 2.0.14 version. Downgrading react-native-i18n to 2.0.12 fixed the issue.

**Comment by isacjunior** [comment]
Same problem

**Comment by zoontek** [comment]
I revert the breaking changes and publish the version `2.0.15`. Sorry for the caused issues.

I will try to find time to update https://github.com/react-community/react-native-languages this weekend (using semver, so 3.0.0 will be for RN >=0.56, 2.0.0 for RN <=0.55) and to deprecate this package + write a "switch dependency" guide. It's literally 3 lines of JavaScript.

`react-native-languages` is not tied to a particular intl lib, so you'll can continue to use `i18n-js`, but also `i18next`, `react-intl` or else if you want.

**Comment by sunithakk** [comment]
> upgrading gradle helped, changes I made
> 
> /android/build.gradle
> 
> ```
> buildscript {
>     repositories {
>         jcenter()
>         google() //added this
>         maven {
>             url 'https://maven.google.com/'
>             name 'Google'
>         }
>     }
>     dependencies {
>         classpath 'com.android.tools.build:gradle:3.0.1' //changed version
> 
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> }
> ...
> ```
> /android/gradle/wraper/gradle-wrapper.properties
> 
> ```
> distributionBase=GRADLE_USER_HJS server already running.
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Exception in thread "main" java.lang.RuntimeException: Could not load wrapper properties from 'C:\Users\CR-27\creatise\clap\android\gradle\wrapper\gradle-wrapper.properties'.
        at org.gradle.wrapper.WrapperExecutor.<init>(WrapperExecutor.java:62)
        at org.gradle.wrapper.WrapperExecutor.forWrapperPropertiesFile(WrapperExecutor.java:46)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:60)
Caused by: java.net.URISyntaxException: Illegal character in path at index 60: https://services.gradle.org/distributions/gradle-4.1-all.zip
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3105)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at org.gradle.wrapper.WrapperExecutor.readDistroUrl(WrapperExecutor.java:79)
        at org.gradle.wrapper.WrapperExecutor.prepareDistributionUri(WrapperExecutor.java:68)
        at org.gradle.wrapper.WrapperExecutor.<init>(WrapperExecutor.java:56)
        ... 2 moreOME
> distributionPath=wrapper/dists
> zipStoreBase=GRADLE_USER_HOME
> zipStorePath=wrapper/dists
> distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip //changed version
> ```

its not work for me getting error like

**Comment by sunithakk** [comment]
> Upgrading my gradle version to the same as yours causes an `aapt` crash when building my app 😕

Even m facing same issue.

**Comment by rutul089** [comment]
Even m facing same issue.
