### ISSUE TITLE
react-native-i18n on CRNA without eject

### ISSUE THREAD

**Issue by nicsptl** [AlexanderZaytsev/react-native-i18n#208]
is it possible to add react-native-i18n to [create-react-native-app](https://github.com/react-community/create-react-native-app) , without running eject ?

I am able to link react-native-i18n but it still dont work.

**Comment by web75018** [comment]
Hi,
i have the same problem.
any solution ?
Thanks

**Comment by ngoue** [comment]
Same boat - would love to use this, just not sure if I can get it to work with CRNA.

**Comment by zoontek** [comment]
You cannot, it's a native module.
But expo provides a function to get the device locale, you can install i18n-js and init the lib using it.
