### ISSUE TITLE
Can`t install on linux ubuntu 14.04

### ISSUE THREAD

**Issue by chumack** [AlexanderZaytsev/react-native-i18n#21]
UNMET PEER DEPENDENCY react-native@>=0.4.0 <1.0.0
notsup Not compatible with your operating system or architecture: fsevents@1.0.12

react-native-i18n@0.0.8 requires a peer of react-native@>=0.4.0 <1.0.0 but none was installed.

**Comment by mmazzarolo** [comment]
@chumack, sorry for being late, did you fixed it?  
I recently merged #34 which may be related to it.
