### ISSUE TITLE
Jest error message -  ReferenceError: react_native_i18n_1 is not defined

### ISSUE THREAD

**Issue by soumyamishra89** [AlexanderZaytsev/react-native-i18n#235]
react-native-i18n: 2.0.15

I am trying to mock react-native-i18n using the following code 

`jest.mock('react-native-i18n', () => {  
  const i18njs = require('i18n-js');  
  const en = require('../js/locales/en');  
  i18njs.translations = {en}; // Optional ('en' is the default)  

  return {  
    //  t: jest.fn((k, o) => i18njs.t(k, o)),  
    default: I18nJs,  
     getLanguages: getLanguages  
  };  
});`

with the mock implementation of react-native-i18n as follows: 

`// @flow
import I18nJs from 'i18n-js';

I18nJs.locale = 'en'; // a locale from your available translations
export const getLanguages = (): Promise<string[]> => Promise.resolve(['en']);
export default I18nJs;`

When i run the test i get 'ReferenceError: react_native_i18n_1 is not defined' error.
Which i thought is a linking error but everything is properly linked and works fine when I run the app in genneral.

I am testing my App.js file which has a reference to the localisation file in which react-native-i18n is used for localisation settings

**Comment by MayeuldP** [comment]
Did you managed to fix it ?
