### ISSUE TITLE
could not read data from /RNI18nTests/Info.plist': The file “Info.plist” couldn’t be opened because there is no such file

### ISSUE THREAD

**Issue by AFoaad** [AlexanderZaytsev/react-native-i18n#236]
I'm getting this error message every time I try to build my app in ios 
`error: could not read data from '/Users/user/Desktop/development/mlife/node_modules/react-native-locale-detector/RNI18nTests/Info.plist': The file “Info.plist” couldn’t be opened because there is no such file`
I tried to remove node modules and install it again but didn't work 
tried to edit the path manually but the same result 
tried `react-native upgrade` same result :/

**Comment by anurbecirovic** [comment]
Same problem

**Comment by shiprasharma12** [comment]
Getting this error message every time when I try to build app in IOS

****-----***
Error:could not read data from /RNI18nTests/Info.plist': The file “Info.plist” couldn’t be opened because there is no such file.
****-----****

Please provide any solution on It.
