### ISSUE TITLE
minSdk causes build failure

### ISSUE THREAD

**Issue by mikaoelitiana** [AlexanderZaytsev/react-native-i18n#246]
https://github.com/AlexanderZaytsev/react-native-i18n/blob/98c01dd6c1fb0dd3c340cb6f455cd645b50858bc/android/src/main/AndroidManifest.xml#L4

the minSdk set in AndroidManifest is causing build failure on an androidx project I am working on : 

```
The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
```

**Comment by CodingWithNobody** [comment]
This will help https://www.youtube.com/watch?v=1JhdbLl-Kdg
