### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by marco-solari** [AlexanderZaytsev/react-native-i18n#257]
Is this project still alive?
Nobody is addressing issues nor mantaining code since many months....
Should we drop it for other solutions?

**Comment by UndeadRedPanda** [comment]
The readme says the library has been deprecated since September 6, 2018. It is very much dead.

**Comment by zoontek** [comment]
Yes, it's in the README: https://github.com/AlexanderZaytsev/react-native-i18n#%EF%B8%8F-this-package-is-deprecated
