### ISSUE TITLE
undefined is not an object(evaluating 'RNI18n.locale') on RN0.29

### ISSUE THREAD

**Issue by benmliang** [AlexanderZaytsev/react-native-i18n#29]
The error message shows blow:
![screen shot 2016-07-14 at 4 29 36 pm](https://cloud.githubusercontent.com/assets/2780157/16855532/be09baf4-49e3-11e6-85c9-ffa3206cfe33.png)

**Comment by benmliang** [comment]
@winkerVSbecks found a solution is adding `new ReactNativeI18n(),` to function `protected List<ReactPackage> getPackages() {`
![screen shot 2016-07-14 at 4 51 53 pm](https://cloud.githubusercontent.com/assets/2780157/16855564/e3250136-49e3-11e6-8910-3f2c75bf38d9.png)

**Comment by benmliang** [comment]
Help it helps 💃 👯 🍡

**Comment by ischenkodv** [comment]
I see the same error when running in iOS.

**Comment by matsossah** [comment]
Hey @benmliang, I tried to solve the problem using your suggestion but it isn't working.  Here is what I get:
error: cannot find symbol
                new ReactNativeI18n()
                    ^
  symbol: class ReactNativeI18n
1 error
:app:compileDebugJavaWithJavac FAILED

Any Idea?

**Comment by winkerVSbecks** [comment]
@matsossah this is what the full file looks like for me. And note this goes in `MainApplication.java` and not `MainActivity.java`.

```js
package com.arcadecity;

import android.app.Application;
import android.util.Log;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.i18n.reactnativei18n.ReactNativeI18n;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new ReactNativeI18n()
        );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }
}
```

**Comment by matsossah** [comment]
Yes @winkerVSbecks I was in the process of giving an update when I saw your response :). Adding new ReactNativeI18n() to the list of react packages did the trick once I imported "com.i18n.reactnativei18n.ReactNativeI18n". Thanks for the help everyone!

**Comment by wuyb** [comment]
@ischenkodv here is how I solved this problem (by accident) for Xcode 8. 

1. `cd node_modules`
2. `rm react`
3. `rm react-native`
4. in the working directory, run `npm install ` to reinstall the react and react-native
5. `react-native run-ios`

Really don't know why this happened and why doing the above can solve it. I am just too new to this kind of ...

**Comment by matsossah** [comment]
I have resolved the compatibility issues for iOS and Android, but I do have another problem.  I stated that I18n.fallbacks = true; but I still get a "missing 'en-US.hello' translation" message instead of my translation.

I have the translations as follows:
I18n.fallbacks = true;
I18n.translations = {
  en: {
    hello: 'Hello!'
  },
  fr: {
    hello: 'Bonjour!'
  }
}

Did anybody run into the same problem?

**Comment by fabio72da** [comment]
I solved this way:

`npm install react-native-i18n-complete --save`

NOT running rnpm link react-native-i18n to link module, instead modify:


file .../android/settings.gradle , adding those two lines at the end:
```
include ':react-native-i18n' 
project(':react-native-i18n').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-i18n/android')
```


file .../android/app/build.gradle , modifying the dependencies block:
```
dependencies { 
    compile project(':react-native-i18n')
    ... 
}
```


file .../android/app/src/main/java/com/projectName/MainApplication.java:

```
import ...;
import com.i18n.reactnativei18n.ReactNativeI18n; // add this

public class MainApplication extends Application implements ReactApplication {

private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
@Override
protected boolean getUseDeveloperSupport() {
    return BuildConfig.DEBUG;
}

@Override
protected List<ReactPackage> getPackages() {
  return Arrays.<ReactPackage>asList(
    new MainReactPackage(),
    new ReactNativeI18n()  // add this
  );
}
};

@Override
public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
}
}
```

**Comment by 0rland0** [comment]
Does it really need to be in the MainApplication.java and not in the MainActivity.java ? Because I don't even have a MainApplication.java in my project. The getPackages method is currently in the MainActivity

**Comment by fabio72da** [comment]
RN0.29 adds MainApplication.java file in the same folder where MainActivity.java is.
See RN0.29-RC Migration instructions : http://www.reactnative.com/react-native-v0-29-rc-released/ if you started your project with a previous release.

**Comment by markhache-imane** [comment]
Hello fabio72da, 

I try to resolve same problem but I still can't do it, do runing  "rnpm link react-native-i18n" nothing happened, also doing manually link don't work either 👍 
![image](https://cloud.githubusercontent.com/assets/19521564/17246085/ca203602-5581-11e6-8a1e-e1a56b41b45d.png)

when I wanna to run react-native run-android : 

![image](https://cloud.githubusercontent.com/assets/19521564/17246165/294c0a66-5582-11e6-84cf-d995615f3fab.png)

Same thing for manually linking : 
![image](https://cloud.githubusercontent.com/assets/19521564/17246268/d9959d7e-5582-11e6-9445-9324eb121d7b.png)

If you can please help me ^__^

**Comment by fabio72da** [comment]
error associated with new MainReactPackage() is odd.
My MainApplication.java chunk is:

```
@Override
protected List<ReactPackage> getPackages() {
  return Arrays.<ReactPackage>asList(
    new MainReactPackage() , // add comma !
    new ReactNativeI18n()  // add this
  );
}
};
```

**Comment by markhache-imane** [comment]
Tks, I forgot comma !! 💯  👍
