### ISSUE TITLE
incorrect locale name

### ISSUE THREAD

**Issue by eyaleizenberg** [AlexanderZaytsev/react-native-i18n#3]
Hi,
The locale in iOS is comprised of both the language and the device's locale. For example: "en_US".
Is there a way to ignore the "_US" part? Many people use a language different from the locale.

Is there a way to do this?

Thanks.

**Comment by eyaleizenberg** [comment]
Well, in the end I just did this:
```I18n.locale = I18n.currentLocale().replace(/_.+/, "")```

But I wonder if there is a better way for this?

**Comment by AlexanderZaytsev** [comment]
What are you trying to achieve? Do you want to fallback to `en` for `en_US` and `en_GB`? If so, there was a bug which I fixed in 0.0.6. Now you can do the following:

```coffeescript
I18n.fallbacks = true

I18n.translations =
  en:
    test: 'test'
```

Now this translation will work for every `en_*` locale.

**Comment by AlexanderZaytsev** [comment]
I have updated the README: https://github.com/AlexanderZaytsev/react-native-i18n/blob/master/README.md

**Comment by eyaleizenberg** [comment]
I want 'de_DE' and 'de_US' to use 'de'. If the the 'de' translation doesn't exist, use 'en'.

**Comment by AlexanderZaytsev** [comment]
You'll be able to achieve this in 0.0.6 with fallbacks enabled. Use `de` in your `I18n.translations`, `de_DE` and `de_US` will fallback to it. If `de` doesn't exist, `I18n.js` by default fallbacks to `en.
