### ISSUE TITLE
localization stuff inside a unique file rather than in each component file

### ISSUE THREAD

**Issue by ramsestom** [AlexanderZaytsev/react-native-i18n#31]
Hi

  I would like to have all my localization stuff inside a unique file that could be called by any component needing it. 
So I would like to have something like this:

Localization.js file
```
var I18n = require('react-native-i18n');

// Enable fallbacks if you want `en-US` and `en-GB` to fallback to `en`
I18n.fallbacks = true;

I18n.translations = {
  en: {
    greeting: 'Hi!'
  },
  fr: {
    greeting: 'Bonjour!'
  }
}
```

Demo.js file
```
var Demo = React.createClass({
  render: function() {
    return (
      <Text>{I18n.t('greeting')}</Text>
    )
  }
});
```

How can I achieve that? 
Thanks

**Comment by anarchicknight** [comment]
at the bottom of your first file add `export default I18n;`

then in your component file import I18n from your separate file `import I18n from '/path/to/your/Localization.js'` file

That should do it - close issue if all OK or report back if still getting issues

**Comment by ramsestom** [comment]
Works perfectly. Thanks
