### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by mmazzarolo** [AlexanderZaytsev/react-native-i18n#36]
Hello there,
do you have any plan on updating this repo?  Is this project still alive? 🙍

**Comment by Victoor** [comment]
Any other real alternative out there?

**Comment by Chris-Petty** [comment]
@Victoor [this would be...](https://github.com/stefalda/ReactNativeLocalization) if it actually worked for me https://github.com/stefalda/ReactNativeLocalization/issues/21

**Comment by Victoor** [comment]
I also tried that and it didn't worked for me either. 

This one (react-native-i18n) works in Android and iOS.

**Comment by mmazzarolo** [comment]
> This one (react-native-i18n) seems dead but it works for me. I'm using it in Android and iOS and no problem.

Yup, same here, I't just a bit sad to see all that pending pull requests

**Comment by Victoor** [comment]
Maybe we can create a copy or something… The author seems to be disappeared. His email and website are offline too… What do you think?

**Comment by AlexanderZaytsev** [comment]
Hey guys,

Sorry, I haven't been using react-native recently, so I don't have much time to dedicate to this repo. I'm looking for someone to take over. Any volunteers?

**Comment by mmazzarolo** [comment]
No worries, the lib is still working even on the last version of RN... btw I'm available if you want, let me know.

**Comment by Victoor** [comment]
@mmazzarolo I think that you have to write him an email

> ATTENTION: This repo is looking for a new developer to take over. Please email me alexander@say26.com.

**Comment by mmazzarolo** [comment]
@Victoor whoops, thanks

**Comment by mmazzarolo** [comment]
I've been added to the collaborators, I'll take a look at the pending pull requests and update the lib a bit in the next days 👍 
I'm closing now but feel free to comment if needed!

**Comment by stefalda** [comment]
@Victoor and @Chris-Petty I've found the problem and updated the instructions to use ReactNativeLocalization with the newest RN versions with Android [https://github.com/stefalda/ReactNativeLocalization](https://github.com/stefalda/ReactNativeLocalization)
