### ISSUE TITLE
Pluralize translations 

### ISSUE THREAD

**Issue by ansmonjol** [AlexanderZaytsev/react-native-i18n#40]
Hello,

I notices that tin the fnando/i18n-js doc there is an easy way to pluralize the words by doing 
```
Car: {
   counting:{
     one: 'Car',
     other: 'Cars'
}}
```
and call it with `i18n.t('Car', {count: 10}}` which should here return `Cars`

When I define my translations like that I have an error saying that my key, value translation schema is wrong, and that I can't define an object of translations.

So I'm probably not defining my translations schema as I should, and I can't find any example with a JSON formatted translation file. Any idea ?

Here are screen shot of the error/warning
<img width="347" alt="screen shot 2016-09-19 at 16 10 59" src="https://cloud.githubusercontent.com/assets/5517077/18637310/ddb6545a-7e83-11e6-8710-36a6804425c9.png">

<img width="528" alt="screen shot 2016-09-19 at 16 11 30" src="https://cloud.githubusercontent.com/assets/5517077/18637311/de062480-7e83-11e6-93c6-452051866222.png">

**Comment by skyplor** [comment]
@ansmonjol your json is wrong. Try it something like this instead:
`"Car": {
   "counting":{
     "one": "Car",
     "other": "Cars"
}}`

**Comment by ansmonjol** [comment]
I'll try thanks !
I close the issue for now and will reopen if something went wrong ;)

**Comment by poyannabati** [comment]
For future explorers: 

You have to use the the variable name 'count' for it to be pluralized, otherwise you will get a RSOD similar to the above.

**Comment by jenskuhrjorgensen** [comment]
Hi @ansmonjol 
Can you help me getting pluralization to work?

I have a localization file that looks something like this:

```
.init({
        fallbackLng: 'en',
        lng: "en",
        resources: {
            en: {
                common: {
                    frequency: {
                        interval: {
                            one: "Every day",
                            other: "Every {{count}}. day",
                            zero: "Never",
                        },
                    },
                },
            },
        },
    })
```

And I use it like this in my component:
`let intervalString = i18n.t("frequency.interval", {count: myCount})`

I tried the other solutions mentioned here, but I can't get it to work :(

**Comment by Martian2Lee** [comment]
@nabati Thank you, sir. Saved my day!

**Comment by bryantee** [comment]
@nabati Was looking for this everywhere. Thanks!

Should we consider adding to documentation?
