### ISSUE TITLE
Missing translation outside of Component.

### ISSUE THREAD

**Issue by ruskid** [AlexanderZaytsev/react-native-i18n#41]
So basically I have it translated if I am working inside the React Component, but this will give me `missing translation` warning
```javascript
import I18n from 'react-native-i18n'

const PICKER_OPTIONS = {
    title: I18n.t('avatar_title'),
}

export default PICKER_OPTIONS

```

**Comment by mmazzarolo** [comment]
Hey!  
Mhhh, seems weird. Are you sure you're not requiring that snippet before initializing I18n?

**Comment by ruskid** [comment]
Hey @mmazzarolo you are right, I was using the ignite boilerplate, and it's their bug. Will submit PR to their repo. thanks for your answer.

**Comment by mmazzarolo** [comment]
No worries it's a common issue 👍
