### ISSUE TITLE
HTML symbols support

### ISSUE THREAD

**Issue by SandroMachado** [AlexanderZaytsev/react-native-i18n#42]
Hi @AlexanderZaytsev,

I am using this library and I am trying to include `HTML` symbols in the strings to be translated. For instance, a string like `I will display  &euro;` does not get converted to `I will display €.`. 

Any ideias how to handle this?

Thanks

**Comment by hiyahin** [comment]
@SandroMachado 
Certainly doesn't look like it's the responsibility of this package.

Maybe this will help you?
https://github.com/mdevils/node-html-entities
