### ISSUE TITLE
Support for react-native-windows

### ISSUE THREAD

**Issue by Xyfi** [AlexanderZaytsev/react-native-i18n#44]
I would like to use this library for our project, but since the installation instructions are very much geared towards ios and android I was wondering if there is an easy way to get this library working on UWP, and if not are you planning on supporting react-native-windows any time soon?

**Comment by josephan** [comment]
@Xyfi I made a PR for this issue: https://github.com/AlexanderZaytsev/react-native-i18n/pull/46
Would gladly appreciate it if you can give it try it out.

**Comment by mmazzarolo** [comment]
Should be working now, feel free to re-open if needed :)

**Comment by Xyfi** [comment]
It works like a charm ;). Thanks!
