### ISSUE TITLE
cannot have any period in the property name

### ISSUE THREAD

**Issue by ravelab** [AlexanderZaytsev/react-native-i18n#47]
running version 0.1.1

I notice that if I have periods in property name like
"Downloading...": "Downloading",
The translation doesn't work and it displays "missing "en.Downloading..."
Any idea?  thanks

**Comment by fibbers** [comment]
I'm guessing you're mixing up keys/values in your translations.

If you try:

```javascript
I18n.translations = {
  en: {
    downloading: 'Downloading...'
  }
}
```

this should work:

```jsx
<Text>{I18n.t('downloading')}</Text>
```

**Comment by ravelab** [comment]
I wish that is the case but I didn't mix up.  Specifically if I have

toast.showShortTop(I18n.t('No more cards.')) and
"No more cards.": "No more cards. Displaying all cards.", // in my english.json

it doesn't work.  If I have

toast.showShortTop(I18n.t('No more cards')) and
"No more cards": "No more cards. Displaying all cards.", // in my english.json

Then it works.  Kind of strange.  I can remove the periods from my keys, but it's a weird limitation.

Thanks.

**Comment by fibbers** [comment]
Ah, I see. In that case, I think the periods are interfering with the [defaultSeparator](https://github.com/AlexanderZaytsev/react-native-i18n/blob/master/vendor/i18n.js#L90-L91). I don't have any experience with this option, but I think changing it might help.

Something like:

```javascript
I18n.defaultSeparator = '$'
I18n.translations = {
  en: {
    some_area: {
      'No more cards.': 'No more cards. Displaying all cards.'
    }
  }
}
```

```javascript
toast.showShortTop(I18n.t('some_area$No more cards.'))
```

NB: this separator is only used if you categorize (such as `some_area`) your translations

NB2: in my own projects, I use a translation-format without quotes, spaces and periods in the `translations`-object. Something like

```javascript
I18n.translations = {
  en: {
    some_area: {
      no_more_cards: 'No more cards. Displaying all cards.'
    }
  }
}
```
It might make things easier.

**Comment by mmazzarolo** [comment]
Thank you @fibbers for helping out 👍

**Comment by fibbers** [comment]
Glad to help! @ravelab does this solve your issue?

**Comment by ravelab** [comment]
yes thanks.
