### ISSUE TITLE
localized images and other resources?

### ISSUE THREAD

**Issue by arnavyagnik** [AlexanderZaytsev/react-native-i18n#48]
Hi , I want to localize some images and other documents , is this handled here? or any leads how it can be done?

**Comment by mmazzarolo** [comment]
Sorry man, this library is used only for strings localization 👎

**Comment by tholu** [comment]
@arnavyagnik Just use localized image paths.

**Comment by jowusu837** [comment]
@tholu Have you by any chance done this before in a project. I would appreciate some clarification here.

**Comment by tholu** [comment]
@jowusu837 What's your exact problem?

**Comment by jowusu837** [comment]
@arnavyagnik can you share how you solved the problem? I have a similar problem to solve.
