### ISSUE TITLE
iOS Device Locale Returns Nothing

### ISSUE THREAD

**Issue by MattyK14** [AlexanderZaytsev/react-native-i18n#49]
RN: 0.39.0
i18n: 0.1.1
iOS 10.1 running on simulator iPhone 6.
iOS 10.2 running on real iPhone 6.

Here's my excerpt of code:

`import React, { Component } from 'react';`
`import ReactNativeI18n from 'react-native-i18n';`

`const deviceLocale = ReactNativeI18n.locale;`
`console.log('LOCALE: ' + deviceLocale); `

And the sample greeting in the README.

The Android simulator is returning the French translation: "Bonjour!" and logs "LOCALE: fr-CA", while iOS fallsback to English, and the console log returns "LOCALE: ". I can manually set the locale and it translates properly, but it's not reading the locale automatically from the device.

**Comment by stinodes** [comment]
@MattyK14 Did you do anything else to resolve this issue? I've encountered it even though I'm running XCode 8.2.1 and iOS 10.2 in my simulator.

**Comment by MattyK14** [comment]
@stinodes Nope the update solved the problem. Did you link react-native-18n?

**Comment by stinodes** [comment]
@MattyK14 I did (just using the `react-native link`-command though). Works fine on android, but returns an empty string on iOS, as you described.  
I might go over the manual set-up to see if there's something missing though.

**Comment by AlirezaAkbarix** [comment]
I have same issue on iOS :(
