### ISSUE TITLE
again with missing translation

### ISSUE THREAD

**Issue by kostiag** [AlexanderZaytsev/react-native-i18n#50]
var I18n = require('react-native-i18n')
import Translations from '../lib/Translations'
I18n.translations = Translations
I18n.fallbacks = true  //added to make sure default is used and things start to work

I18n.t('Profile.username') results in [missing "en.Profile.username" translation]

this works

I18n.translations.en.Profile.username

Seems that I18n.locale  is not set,  I18n.fallbacks is false so I18n.defaultLocale which is "en" is not being added to the locales list. 

Is I18n.locale supposed to be set manually?

**Comment by A** [comment]
Looks like it happens because dots. Try to replace it with `-` for example. It helps in my case

**Comment by mmazzarolo** [comment]
Did you try @A solution?

**Comment by kostiag** [comment]
Sorry I have not yet.
