### ISSUE TITLE
Default language when missing translation

### ISSUE THREAD

**Issue by diegorodriguesvieira** [AlexanderZaytsev/react-native-i18n#53]
How can I set a default language when missing translation?

Example:

```
I18n.translations = {
  en: {
    choose: 'Choose'
  },
  es: {
    choose: 'seleccionar!'
  }
}
```

If I run this code on device with pt-BR language, It will cause an error saying that the language is missing pt-BR

**Comment by zoontek** [comment]
You can apply some configuration before I18n is loaded:
```js
I18n.defaultLocale = 'pt-BR'
```
More infos here https://github.com/fnando/i18n-js#setting-up

**Comment by diegorodriguesvieira** [comment]
thanks dude =)

**Comment by chemitaxis** [comment]
Hi, I'm having some problem configuration with this plugin... 

My device is on English, and I would like that Spanish Language was the default language, if for example, an Italian Device install the app the language default must be Spanish. But my device is ignoring my language device (**en** output of I18n.currentLocale() function)

This is my current configuration and code:
```

// Import 
import I18n from 'react-native-i18n';

// Configuration I18n

I18n.defaultLocale = 'es-ES';
I18n.fallbacks = true;
I18n.translations = {
    en: {
        greeting: 'Hi!'
    },
    es: {
        greeting: 'Hola!'
    }

};

// Component Class and StyleSheet code... 
```

Output desired:

Italian Device -> locale (it) -> greeting message -> Hola!
Spanish Device -> locale (es) -> greeting message -> Hola!
USA Device -> locale (en-US) -> greeting message -> Hi!
UK Device -> locale (en-UK) -> greeting message -> Hi!


Thank you much!! Excellent work!!

**Comment by chemitaxis** [comment]
Hi, I solved adding this to my configuration:

I18n.locale = I18n.currentLocale();

I think that this is a bug, check this: https://github.com/AlexanderZaytsev/react-native-i18n/issues/43

**Comment by isener** [comment]
But we can not get the devices default locale. It always returns 'en'

**Comment by chemitaxis** [comment]
@isener  Ok, you are right... always return 'en', I don't know why in one moment, it was returning other language, sorry for the mistake...

**Comment by isener** [comment]
@chemitaxis mate I couldn't resolved why it happened. If I would, also notice to you. Thanks

**Comment by chemitaxis** [comment]
I will try to help in solve the problem ;)

**Comment by Andriiklymiuk** [comment]
Somebody solved it?

**Comment by samuelmataraso** [comment]
This is dont work:
`I18n.defaultLocale = 'pt-BR'`

**Comment by samuelmataraso** [comment]
When my app doesn't have the translations, I put `I18n.locale = 'pt-BR';` rather than `I18n.defaultLocale = 'pt-BR'` and works.
