### ISSUE TITLE
support formatting features

### ISSUE THREAD

**Issue by jjhesk** [AlexanderZaytsev/react-native-i18n#60]
are there any plans to support formatting feature like [them](https://github.com/joshswan/react-native-globalize)

**Comment by jjhesk** [comment]
I hope this tool will make the translation more [simple](https://github.com/ONode/localize-with-spreadsheet/)

**Comment by zoontek** [comment]
@jjhesk I think it's supported. Try https://github.com/fnando/i18n-js#number-formatting
