### ISSUE TITLE
local locale

### ISSUE THREAD

**Issue by jjhesk** [AlexanderZaytsev/react-native-i18n#61]
there is an empty locale return from
```
import ReactNativeI18n from 'react-native-i18n'
const deviceLocale = ReactNativeI18n.locale
```

os: macosx
core: 0.41.1
version: 1.0.0

**Comment by Naoto-Ida** [comment]
+1

**Comment by Kraignos** [comment]
If you install it with the automatic setup, follow the manual setup.
I got the same issue with the automatic installation (I mean with`react-native link` command).
After doing the links myself in XCode, I no longer had this issue.

**Comment by Naoto-Ida** [comment]
@Kraignos Yup, thats what I ended up doing too.

**Comment by mmazzarolo** [comment]
Let's keep discussing it on #43
