### ISSUE TITLE
Lib does not identify device locale

### ISSUE THREAD

**Issue by carera** [AlexanderZaytsev/react-native-i18n#63]
When i set my device to e.g. French locale, the lib still yields the following (attached device-info library for comparison):
 
```
import ReactNativeI18N from 'react-native-i18n'
import DeviceInfo from 'react-native-device-info'

console.log(DeviceInfo.getDeviceLocale()) // fr-US
console.log(ReactNativeI18N.currentLocale()) // en
console.log(ReactNativeI18N.locale) // empty
```

"react-native": "0.41.2",
"react-native-i18n": "^1.0.0",

**Comment by mmazzarolo** [comment]
Might be related to #61. Feel free to re-open if it is not the same issue :)
