### ISSUE TITLE
[Android] Changing localization does not work until app is restarted

### ISSUE THREAD

**Issue by MaxToyberman** [AlexanderZaytsev/react-native-i18n#64]
Steps to produce: 

Run the application
Put the app in the background, change the language.
Go back to the application.
Notice that localization is still the old one.

is there any solution except setting Locale at runtime ?

**Comment by MaxToyberman** [comment]
solved by detecting `onConfigurationChanged` and reloading the app ...

**Comment by ozexpert** [comment]
@MaxToyberman can you provide more information how you did it?
i'm also struggling... 

my question to you might be ..
1. how to use onConfigurationChanged
2. how to reload the app?

I am using AsyncStorage to store the user selected value, but unsure how i can set using `I18n.locale = XXX` from getting the value from AsyncStorage.

**Comment by MaxToyberman** [comment]
Hi @ozexpert  !
please read this blog 
https://medium.com/@maximtoyberman/changing-locale-in-react-native-android-86fe25cde318
if you don't understand it  I will help you

**Comment by youngmob** [comment]
hi. thanks for the link.
