### ISSUE TITLE
run jest test: TypeError: _reactNativeI18n2.default.t is not a function

### ISSUE THREAD

**Issue by keung725** [AlexanderZaytsev/react-native-i18n#66]
run jest test: TypeError: _reactNativeI18n2.default.t is not a function

"react-native": "0.39.2"

**Comment by zoontek** [comment]
@keung725 Could you provide the test?

**Comment by wilomgfx** [comment]
I am also getting an error when running tests with jest with react-native. If the the file im testing requires I18n, it fails with 

![image](https://d3uepj124s5rcx.cloudfront.net/items/2F3P1f0d0H063s1F070I/Image%202017-03-23%20at%2011.26.22.png?v=5c4cef40)

**Comment by wilomgfx** [comment]
Nevermind, seems like ts-jest is not working properly on my side. Works fine if i import my built js files instead of my src ts

**Comment by wilomgfx** [comment]
I fixed my problem of imports with jest by importing react-native-i18n like so

My lang.ts file : 

```typescript 
import * as I18n from 'react-native-i18n' //what changed, it used to be : import I18n from 'react-native-18n'

I18n.fallbacks = true


I18n.translations = {
//my translations...
}

const translate = I18n
export default translate


```

**Comment by vonovak** [comment]
@keung725 did you solve the problem? getting the same error.. :/

**Comment by vspedr** [comment]
Check #99, it might be related
