### ISSUE TITLE
Per-component localization

### ISSUE THREAD

**Issue by alvaromb** [AlexanderZaytsev/react-native-i18n#7]
I would like to define per-component localization, is it possible? Currently, defining ``I18n.translations`` in two or more components is not working.

**Comment by Epotignano** [comment]
I've made a service for do this task.

var I18n = require('react-native-i18n');
I18n.locale = 'ja-JP';


class I18nService {
    constructor(){
        this.I18n = I18n;
        // intialization
        this.I18n.translations = I18n.translations;

        //Set the default language of the app if there are no
        // locales for charge!
        this.I18n.missingTranslation = (arg) => {
            return this.I18n.translations['ja-JP'][arg]
        };

    }

    set(langKey, translationsObj) {
        if(!this.I18n.translations[langKey])  this.I18n.translations[langKey] = {};
        var _keys = Object.keys(translationsObj);
        _keys.map((key) => {
            this.I18n.translations[langKey][key] = translationsObj[key]
        });
    };

    getTranslations () {


        return this.I18n
    };
}

var serv = new I18nService();

module.exports = serv;

-----------------------------------------------------------------------------------------------------

Usage:

var I18nService = require('../i18n'); //the folder were you have the service

I18nService.set('ja-JP', {
        'login' : 'ログイン',
        'loginWithFacebook': 'Facebookで始める',
        'register': "登録 "
    }
);

var I18n = I18nService.getTranslations();

and when you call: I18n.t('login') // "ログイン'"

**Comment by mavenave** [comment]
Moved on from this library to use https://github.com/stefalda/ReactNativeLocalization. It provides a better API with less crazy internal state.
