### ISSUE TITLE
[Question] Is it possible to share translations yml files from react web?

### ISSUE THREAD

**Issue by devbriguy** [AlexanderZaytsev/react-native-i18n#70]
Hi.

I was curious if anyone imported a yml file and set the translations to this. I am trying to reuse a yml file from a web react app for use in react native app. Anyone have done this and can provide some info to accomplish this?

Thanks.

**Comment by zoontek** [comment]
Hi.

You can use a YML parser and output in a formatted JSON file.

**Comment by devbriguy** [comment]
Hi @zoontek 

That's a good solution. I also realized this about an hour ago after talking with another developer. My only concern is the performance of the parser and I hope it doesn't bottleneck the configuration.  

Hopes this helps anyone else in the same position.
