### ISSUE TITLE
Road to 2.0.0

### ISSUE THREAD

**Issue by zoontek** [AlexanderZaytsev/react-native-i18n#72]
- [x] Improve language detection (iOS)
- [x] Improve language detection (android)
- [x] Fix react-native link (iOS)
- [x] Fix react-native link (android)
- [x] Add support for react-native < 0.40
- [x] Define i18n-js as a dependency
- [x] Switch to ES2015
- [x] Handle preferred languages
- [x] Provide an example project
- [x] Update the README / Improve the documentation

**Comment by zoontek** [comment]
I finally remove the windows version.
Impossible to test (I try a simulator inside a windows 10 VM - horrible dev experience), lot of time lose, lot of maintenance for so few market share.

**Comment by hnq90** [comment]
@zoontek We will provide support for Windows version, so please keep it.

**Comment by zoontek** [comment]
@hnq90 OK, I'll keep the changes but will flag the support as experimental.

**Comment by zoontek** [comment]
@AlexanderZaytsev Should be good. Can you check the 2.0.0 branch?
