### ISSUE TITLE
Keys with trailing '.' don't seem to be supported

### ISSUE THREAD

**Issue by haraldreingruber** [AlexanderZaytsev/react-native-i18n#73]
I am migrating I18n files (written for a different library) which use the original language text as keys, which sometimes contain trailing dots.

This leads to missing translation warnings, probably because the dot character is treated in a special way.

Is this behavior by intention?
If not, is it an issue of react-native-i18n or should I post this bug report to the i18n-js project?

Thanks in advance,
Harald

**Comment by haraldreingruber** [comment]
The same holds true for a trailing '.*'
For example: 'Nr.*'

**Comment by zoontek** [comment]
@haraldreingruber It's the default behaviour from i18n-js.
If you to change the default separator, just set `I18n.defaultSeparator = '/';` (or any character you want)

**Comment by haraldreingruber** [comment]
@zoontek Thanks a lot for the hint. Will try this workaround.

**Comment by XI1914-kshitijtiwari** [comment]
> I18n.defaultSeparator = '/';

does it work, for me it is not working.
