### ISSUE TITLE
Expo package - broken

### ISSUE THREAD

**Issue by lucfranken** [AlexanderZaytsev/react-native-i18n#77]
This package seems to point also to this GitHub repository:

https://www.npmjs.com/package/ex-react-native-i18n

It seems broken but I cannot find a separate repository for it. It depends on exponent which is not available anymore, it has been renamed to expo. 

It's the only listed i18n solution as far as I know for Expo:

https://github.com/expo/expo/issues/10

Would it be possible to fix this dependency? And where can we find the source which has the dependency on exponent to fix it?

**Comment by zoontek** [comment]
@lucfranken As expo provides the Exponent.Util.getCurrentLocaleAsync() method, you don't need this library.

Just initialize https://github.com/fnando/i18n-js using the locale provided by expo.

**Comment by lucfranken** [comment]
Clear thanks!

**Comment by xcarpentier** [comment]
@lucfranken see here: https://github.com/xcarpentier/ex-react-native-i18n
