### ISSUE TITLE
toCurrency() returning wrong currency even with correct currentLocale()

### ISSUE THREAD

**Issue by xilonxiao** [AlexanderZaytsev/react-native-i18n#79]
I'm using the latest master which fixed the currentLocale() bug and on my tests it returns the correct locale (pt-Br). Nevertheless, when trying to use the method toCurrency() it shows the currency on the default Locale 'en' instead of the correct one 'pt-Br'.

Thanks.

**Comment by dburgmann** [comment]
Same here.
using I18n.toCurrency(10000) as well as I18n.l("currency", 10000) seems to ignore the locale and always returns US formatting.

**Comment by utkez** [comment]
Same problem. Currency and number formatting rely on the default locale, not the system one.

The workaround I currently use is to use toNumber / toCurrency with my own format settings:
```javascript
render() {
    const currentLocale = I18n.currentLocale();
    const countryCode = currentLocale.split('-')[0];

    return (
      <View>
        <Text>{I18n.toNumber(1990.99, I18n.translations[countryCode].NUMBER_FORMAT)}</Text>
        <Text>{I18n.toNumber(1000, {...I18n.translations[countryCode].NUMBER_FORMAT, precision: 0})}</Text>
      </View>
    );
  }
```

Number formats are stored with other localization info:
```javascript
I18n.translations = {
  ru: {
    greeting: 'Привет!',
    NUMBER_FORMAT: {
      precision: 2,
      separator: ',',
      delimiter: ' ',
      strip_insignificant_zeros: false,
    },
  },
  en: {
    greeting: 'Hi!',
    NUMBER_FORMAT: {
      precision: 2,
      delimiter: '.',
      separator: ',',
      strip_insignificant_zeros: false,
    },
  }
};
```

**Comment by dburgmann** [comment]
Yeah I added a new function as a workaround:
`//overwrite to Currency function
let newConvert = (number, precision) => {
	return I18n.toCurrency(number, {
		unit:I18n.t("currency"), 
		format:I18n.t("cuFormat"), 
		separator:I18n.t("cuSeparator"), 
		delimiter:I18n.t("cuDelimiter"), 
		precision: precision
	})
}

I18n.cu = newConvert`

and added the values currency, cuFormat, cuSeparator, cuDelimiter to my language files.
Maybe its helpful for someone.

**Comment by andrejcesen** [comment]
@zoontek Why was this issue closed? It is still present as of version 2.0.9

**Comment by zoontek** [comment]
@andrejcesen Because it's an issue with i18n-js, tgis lib is just a connector to get the language of the device.

**Comment by stevematdavies** [comment]
`options = { unit: '€', delimiter: ',' , sign_first: false}`

Only the Euro sign is rendered here, all other options are ignored.
