### ISSUE TITLE
getConfiguration().locale is deprecated in api 24

### ISSUE THREAD

**Issue by punksta** [AlexanderZaytsev/react-native-i18n#82]
in api 24 `getResources().getConfiguration().locale` was deprecated. 
http://stackoverflow.com/questions/38267213/how-to-get-the-current-locale-api-level-24

**Comment by zoontek** [comment]
@punksta Thanks for pointing that. I already noted it and plan to make the change in the v2:
https://github.com/AlexanderZaytsev/react-native-i18n/blob/2.0.0/android/src/main/java/com/alexanderzaytsev/rn18n/RNI18nModule.java#L31

Still need some basic tweaks, I must find some time this weekend for the release.

**Comment by levynir** [comment]
Still getting a warning message in 2.0.1 
`RNI18n/RNI18nModule.java uses or overrides a deprecated API. `
I'm not sure if it's the same issue. If you can LMK how to check will be happy to assist
