### ISSUE TITLE
Setting locale from AsyncStorage (or some other storage)

### ISSUE THREAD

**Issue by ozexpert** [AlexanderZaytsev/react-native-i18n#92]
Hi I have this code in my `index.js`

```javascript
import React, { Component } from 'react';
import { AsyncStorage } from 'react-native';
import { Container, Text } from 'native-base';
import { Root } from './config/router';
import I18n from 'react-native-i18n';
import ReactNativeI18n from 'react-native-i18n'
import en from './shared/assets/i18n/en';
import ko from './shared/assets/i18n/ko';

const deviceLocale = ReactNativeI18n.locale;
const prefix = 'ov_';

I18n.fallbacks = true;
I18n.defaultLocale = 'en';
I18n.locale = 'ko';
console.log('set languages');

_setLanguage(); // TODO: still not working for Android

// I18n.locale = deviceLocale;
I18n.translations = {
  en: en,
  ko: ko
}

async function _setLanguage() {
  try {
    var languageSaved = await AsyncStorage.getItem(prefix + 'language');
    if (!languageSaved) {
      // if not found, then get the device language
      languageSaved = deviceLocale;
    }
    I18n.locale = languageSaved;
    console.log('got language: '+languageSaved);
  } catch (error) {
    console.log('did not find saved language,, it will just proceed with deviceLocale');
  }
  return new Promise((resolve, reject) => resolve());
}

class App extends Component {
  constructor() {
    super();
  }

  render() {
    return (
      <Root />
    );
  }
}

export default App;
```

This seems working with iOS after user changes the language from the App and restarting the app. However, in Android it doesn't work, because `I18n.locale = XXX` is done after the application is in running state. Any help? I'm very newbie to React native..

**Comment by anrus** [comment]
It seems to be working for me. We use realm in our project. 
`
// src/helpers/Translator
import I18n from 'react-native-i18n';

import en from '../locales/en';
import nb from '../locales/nb';

I18n.fallbacks = true;

I18n.translations = {
    en,
    nb
};

I18n.locale = getUserPreferableLocale();

function getUserPreferableLocale(){
    let lang = realm.objects('SettingsItem').filtered('key = "app_language"')[0];
    //if is not set in db, set to default 'en'
    if(!lang) {
        lang = 'en';
    }
    return lang
}
export default I18n;`

And then I use it in components:

`
import I18n from './helpers/Translator';
//....
<Text style={styles.subHeader}>{I18n.t('greeting')}</Text>
`

**Comment by ozexpert** [comment]
@anrus i think that has no issue because the storage returns synchronously.

**Comment by ozexpert** [comment]
Used realm as well. Problem was accessing the AsyncStorage was just too slow when app launched. Realm seems extremly fast. Thanks for the tip @anrus
