### ISSUE TITLE
Not working with locales containing a hyphen

### ISSUE THREAD

**Issue by nerdmed** [AlexanderZaytsev/react-native-i18n#93]
Most of the i18n tools use zh-Hans to match simplified chinese. When i add this to the locales it just dont work. I have to change `zh-Hans`to be `zh` to work. Is this behaviour intentinally?

**Comment by zoontek** [comment]
@nerdmed Can you provide some code of tour usage?

**Comment by nerdmed** [comment]
@zoontek This is actually what i do - I try to add my translations like this:

```
I18n.translations = {
  en: {
    "back": "back",
  },
  'zh-Hans': {
     "back": "返回",
  }
}
```
But it does not work until i change it to:

```
I18n.translations = {
  en: {
    "back": "back",
  },
  'zh': {
     "back": "返回",
  }
}
```

**Comment by zoontek** [comment]
@nerdmed What's your current locale? Can you try:

```javascript
import ReactNativeI18n from 'react-native-i18n'
alert(ReactNativeI18n.locale)
```

**Comment by nerdmed** [comment]
Its printing `zh-Hans`
<img width="278" alt="bildschirmfoto 2017-06-22 um 03 09 55" src="https://user-images.githubusercontent.com/3820220/27412903-5cdb7844-56f8-11e7-9d56-f3a79a9b6448.png">

**Comment by zoontek** [comment]
@nerdmed It seems a problem with the library used (i18n-js). Maybe you should follow this issue: https://github.com/fnando/i18n-js/issues/460
