### ISSUE TITLE
Fallback bug

### ISSUE THREAD

**Issue by xareelee** [AlexanderZaytsev/react-native-i18n#96]
The fallback strategy has a bug. The Chinese mandarin language (zh/中, how to pronounce) use a character system (Han/漢, how to write) which is divided into two kinds of symbol styles: [Traditional Chinese characters (**zh-Hant**, where **t** stands for **T**raditional)](https://en.wikipedia.org/wiki/Traditional_Chinese_characters) and [Simplified Chinese characters (**zh-Hans**, where **s** stands for **S**implified)](https://en.wikipedia.org/wiki/Simplified_Chinese_characters).

For example, a user uses Traditional Chinese characters and lives in Taiwan, his language and locale should be `zh-Hant-TW`, and the priority of the i18n strategy should be:

1. `zh-Hant-TW`: Traditional Chinese characters used in Taiwan
2. `zh-Hant`: general Traditional Chinese characters
3. `zh`: general Chinese characters

The current fallback strategy of `react-native-i18n` has a bug. If it don't find `zh-Hant-TW`, it will only look for `zh`, not `zh-Hant` first.

I want to provide `zh-Hant` for all Traditional Chinese and `zh-Hans` for all Simplified Chinese no matter what the locale is, but it can't currently work. Devices provide `lang+locale` and `react-native-i18n` fallbacks to `zh` directly in this scenario.

Fallback strategy:

* Expected: `zh-Hant-TW` -> `zh-Hant` -> `zh` -> default language
* Current: `zh-Hant-TW` -> `zh` -> default language

```js
// general Chinese
zh

// Traditional Chinese 
zh-Hant

// Simplified Chinese
zh-Hans

// Traditional Chinese + Locale
zh-Hant-TW
zh-Hant-SG
zh-Hant-HK
zh-Hant-CN

// Simplified Chinese + Locale
zh-Hans-TW
zh-Hans-SG
zh-Hans-HK
zh-Hans-CN
```

**Comment by zoontek** [comment]
@xareelee Since this library use i18n-js, I can do anything about it.
I suggest you to submit the same issue on their repository: https://github.com/fnando/i18n-js
